### ISSUE TITLE
Clone AWS machine image to missing opt-in regions

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#100]
Newly supported AWS regions added on #96 don't include the following:

- af-south-1
- ap-east-1
- eu-south-1
- me-south-1

Once we [opt-in](https://docs.aws.amazon.com/general/latest/gr/rande-manage.html#rande-manage-enable), it would be matter of updating this list and running [`clone-amis.go`](https://github.com/iterative/terraform-provider-iterative/blob/master/cml/clone-amis.go) to clone the image to the missing regions.

**Comment by casperdcl** [comment]
ping @JIoJIaJIu

**Comment by 0x2b3bfa0** [comment]
Context: [#infrastructure/1616585959001200](https://iterativeai.slack.com/archives/C01R00PPQ1L/p1616585959001200) & [#infrastructure/1616586175002700](https://iterativeai.slack.com/archives/C01R00PPQ1L/p1616586175002700?thread_ts=1616585986.002000&cid=C01R00PPQ1L).

**Comment by JIoJIaJIu** [comment]
I've enabled the following AWS regions:
* af-south-1
* ap-east-1
* eu-south-1
* me-south-1

**Comment by duijf** [comment]
@JIoJIaJIu since you assigned me to this one: what's left on this ticket / is there anything that you'd like my help with specifically? :smile:

**Comment by 0x2b3bfa0** [comment]
@duijf, there isn't anything “left” on this ticket beyond running Packer with the code from #206 after reviewing and merging https://github.com/iterative/viewer-itops/pull/82

**Comment by duijf** [comment]
Thanks @0x2b3bfa0! Just reviewed the PR :)

**Comment by 0x2b3bfa0** [comment]
Can we change the region compatibility of session tokens for global endpoint to **Valid in all AWS Regions**? Packer is requesting session tokens from the global endpoint and it fails for those regions.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-manage-tokens
https://aws.amazon.com/es/premiumsupport/knowledge-center/iam-validate-access-credentials/

**Comment by duijf** [comment]
@0x2b3bfa0 Addressed! Also let others know internally in `#infrastructure` so folks are aware if there is any weirdness related to this

**Comment by 0x2b3bfa0** [comment]
✅  Done! Thank you very much for all your help! 🙏🏼
