### ISSUE TITLE
Improve the AWS VPC architecture

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#107]
(Follow-up of https://github.com/iterative/cml/issues/484)

We're using the [first VPC](https://github.com/iterative/terraform-provider-iterative/blob/5520e8376b2fde241bd95b2685723c16f286c62e/iterative/aws/provider.go#L107) and [the first subnet](https://github.com/iterative/terraform-provider-iterative/blob/5520e8376b2fde241bd95b2685723c16f286c62e/iterative/aws/provider.go#L203) to deploy EC2 instances, but this behavior can be problematic in some cases.

We can either create a new VPC as part of the provisioning process or just allow users to specify which one should be used. The first solution could be more transparent for users and allow us to keep the common interface as pure as possible.

**Comment by haviland-nh** [comment]
First posting here!

Just wanted to add an upvote here to provide VPC and Subnet as a parameter.  I think this feature would add flexibility to the provider, without requiring it to do more than it has to.

**Comment by DavidGOrtega** [comment]
We have to create the network resource. This is not new actually nor anything that we have decided recently. In the very beginning the provider needed to have to additional resources:
 - Network
 - Volumes

The network resource will be a very simple network abstraction on top of the cloud vendors. The goal is to have like CML a very yet powerful implementation and the major goal to solve here for ML purposes is the need to create clusters of machines that allow us to do distributed training.
Achieving that goal we will also provide that reusable network where all the basic needs are going to be covered, similar to any cloud vendor capabilities.

**Comment by 0x2b3bfa0** [comment]
Closing in favor of #123 and children

**Comment by 0x2b3bfa0** [comment]
Reopening after the organization, related to (but not mixed with) #124

**Comment by dacbd** [comment]
I think we can close this, a target vpc can be selected with `aws_security_group` and a target subnet with `aws_subnet_id`

perhaps a larger "networking" issue exists so that this can functionally exist with gcp/az @0x2b3bfa0 ?

**Comment by 0x2b3bfa0** [comment]
Related to #289 and #299; more specifically to making use of existing resources.

Yes, we can close this for the reasons you mention.
