### ISSUE TITLE
Be able to reuse a machine or runner

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#122]
Coming from [here](https://discord.com/channels/485586884165107732/728693131557732403/849663507330891836) 

We could shutdown the machine instead of terminate it. It could be a parameter.

**Comment by 0x2b3bfa0** [comment]
I'm inclined to think that reusable storage is a much better solution and this proposal would have two major downsides:
* Instances will preserve the system state between runs, not just the cached training data. This could eventually affect security and stability in the target system; system disks are expected — or so I think — to be pristine for each run.
* Maintaining this feature over every provider could be hard, especially for container orchestrators, where the system doesn't run from a stateful block device.

**Comment by DavidGOrtega** [comment]
What do you think @casperdcl ?

**Comment by casperdcl** [comment]
- if it's only about storage then yes, this may be an X-Y problem and simply supporting volumes would mostly fix the issue
- however, if there are other use cases then this is still a valid feature request. GH self-hosted runners are always-online, for example

**Comment by 0x2b3bfa0** [comment]
> _GitHub self-hosted runners are always-online, for example_

If you mean that they can listen for and run multiple jobs in the same non-isolated environment, yes they do. <sup>[[1](https://docs.github.com/es/actions/learn-github-actions/security-hardening-for-github-actions#hardening-for-self-hosted-runners), [2](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories)]</sup> The question is: if we support shareable storage, would users benefit from this persistence [anti-]feature?

**Comment by casperdcl** [comment]
I'd suggest we wait for someone to actually propose a non-solvable-by-volumes use case and in the meantime close this issue for now.

**Comment by 0x2b3bfa0** [comment]
So be it
