### ISSUE TITLE
Support multi-machine parallel training in a common network

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#127]
@DavidGOrtega suggested that we could also support parallel training by launching many instances on a single private network, where one of them (leader) would run the CML job and the others (followers) would run the job parts sent by the machine learning framework.

@DavidGOrtega, feel free to edit the main issue description and extend/overwrite it as you want.

**Comment by DavidGOrtega** [comment]
This is something that should fix the network itself.

Ideally the scenario would be setting the runner and its peers (non runners) in the same network being the users ML library the one that manages that.
However there are some questions:
 - align ami vs docker usage

**Comment by 0x2b3bfa0** [comment]
Closed with #237 unless proven otherwise; leader election is not implemented yet.
