### ISSUE TITLE
Using our Amazon Machine Images to provision Kubernetes nodes

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#150]
coming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/857243775536726016)

> I have been trying to use your base AWS AMI (260760892802/iterative-cml) image for running k8s job on a selfhosted k8s cluster on AWS. I couldnt get access to the GPU initially, but following the suggestion https://github.com/NVIDIA/k8s-device-plugin/issues/250#issuecomment-848678925 have allowed me to access the GPUs from the k8s pod.. 
I wonder if you would be able to rebuild the AMI image and set the default docker runtime to be "default-runtime": "nvidia"

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 🤔 ?

**Comment by 0x2b3bfa0** [comment]
That's not about our Kubernetes support, but rather about using our AMI for provisioning a Kubernetes node?

**Comment by 0x2b3bfa0** [comment]
We don't officially support this use case yet, but configuration over a generic AMI should be straightforward.

## See also
- https://github.com/NVIDIA/k8s-device-plugin/issues/168
- https://github.com/NVIDIA/k8s-device-plugin/issues/250
- https://github.com/NVIDIA/k8s-device-plugin#preparing-your-gpu-nodes

**Comment by 0x2b3bfa0** [comment]
Would cause https://github.com/iterative/cml/issues/611

**Comment by 0x2b3bfa0** [comment]
Closing unmerged because, as stated, we don't need this functionality and it would introduce some additional issues.
