### ISSUE TITLE
startup_script is 64encoded again if passed as base64

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#168]
If you pass a base64 startup script its encoded again

**Comment by 0x2b3bfa0** [comment]
See also #91?

**Comment by DavidGOrtega** [comment]
If #91 is not merge nor fixed... why is it happening 🤔 ?

**Comment by 0x2b3bfa0** [comment]
This should not happen, at least not for `resource_cml_runner`

https://github.com/iterative/terraform-provider-iterative/blob/aec00d68d84c82d6bcb81e8da6720732b284811e/iterative/resource_runner.go#L438

Can you provide additional context and a minimal example?

**Comment by pmrowla** [comment]
This issue still affects `resource_machine` and makes it impossible to specify a startup script if you are using JSON (`.tf.json`) instead of HCL config files. The heredoc syntax has to be b64 encoded before writing to `main.tf.json` (to avoid having any invalid characters in the JSON string), and then it gets doubly encoded again by TPI.

In the short term we can work around this on the DVC side by using HCL for now, but this will eventually be a blocker for us.

**Comment by pmrowla** [comment]
given this `main.tf.json`:

```json
{
  "//": "This file auto-generated by dvc-tpi, do not edit manually.",
  "terraform": {
    "required_providers": {
      "iterative": {
        "source": "iterative/iterative"
      }
    }
  },
  "provider": {
    "iterative": {}
  },
  "resource": {
    "iterative_machine": {
      "peter-test": {
        "name": "peter-test",
        "cloud": "aws",
        "startup_script": "PDxFT0YKIyEvYmluL2Jhc2gKc3VkbyBhcHQtZ2V0IHVwZGF0ZQpzdWRvIGFwdC1nZXQgaW5zdGFsbCAtLXllcyBweXRob24zIHB5dGhvbjMtcGlwCnB5dGhvbjMgLW0gcGlwIGluc3RhbGwgLS11cGdyYWRlIHBpcAoKY2QgL2V0Yy9hcHQvc291cmNlcy5saXN0LmQKc3VkbyB3Z2V0IGh0dHBzOi8vZHZjLm9yZy9kZWIvZHZjLmxpc3QKc3VkbyBhcHQtZ2V0IHVwZGF0ZQpzdWRvIGFwdC1nZXQgaW5zdGFsbCAtLXllcyBkdmMKCkVPRg=="
      }
    }
  }
}
```

I would expect the machine to be created with this startup script:
```
<<EOF
#!/bin/bash
sudo apt-get update
sudo apt-get install --yes python3 python3-pip
python3 -m pip install --upgrade pip

cd /etc/apt/sources.list.d
sudo wget https://dvc.org/deb/dvc.list
sudo apt-get update
sudo apt-get install --yes dvc

EOF
```

I've tried using the b64 encoded version of the script both with and without the heredoc `<<EOF...EOF`, but as far as I can tell neither one works right now.

**Comment by 0x2b3bfa0** [comment]
@pmrowla, not saying it's a proper fix, but... 🙃  

```json
{
  "//": "This file auto-generated by dvc-tpi, do not edit manually.",
  "terraform": {
    "required_providers": {
      "iterative": {
        "source": "iterative/iterative"
      }
    }
  },
  "provider": {
    "iterative": {}
  },
  "resource": {
    "iterative_machine": {
      "helio-test": {
        "name": "helio-test",
        "cloud": "aws",
        "startup_script": "${base64decode(\"IyEvYmluL2Jhc2gKc3VkbyBhcHQtZ2V0IHVwZGF0ZQpzdWRvIGFwdC1nZXQgaW5zdGFsbCAtLXllcyBweXRob24zIHB5dGhvbjMtcGlwCnB5dGhvbjMgLW0gcGlwIGluc3RhbGwgLS11cGdyYWRlIHBpcAoKY2QgL2V0Yy9hcHQvc291cmNlcy5saXN0LmQKc3VkbyB3Z2V0IGh0dHBzOi8vZHZjLm9yZy9kZWIvZHZjLmxpc3QKc3VkbyBhcHQtZ2V0IHVwZGF0ZQpzdWRvIGFwdC1nZXQgaW5zdGFsbCAtLXllcyBkdmMK\")}"
      }
    }
  }
}
```

**Comment by 0x2b3bfa0** [comment]
```python
import base64
def escape(script: str) -> str:
    encoded = base64.b64encode(b"hello").decode()
    return f"""${{base64decode("{encoded}")}}"""
```

**Comment by 0x2b3bfa0** [comment]
@casperdcl, how would this fit in [iterative/tpi](https://github.com/iterative/tpi)? I guess that you can get rid of HCL2 once and for all.

**Comment by pmrowla** [comment]
Ok, that was my misunderstanding then. I was assuming that in JSON, the terraform provider needed `startup_script` to be b64 encoded since that is how it is ends up being encoded in the tfstate JSON.

`iterative/tpi` already works as-is whether the user is using the HCL `render_template` or the JSON `render_json` to generate the terraform config. `iterative/tpi` just expects the user to pass their `startup_script` as a (multiline) string, and either dumps the string directly as JSON, or adds the heredoc wrapper in the templated HCL.

**Comment by 0x2b3bfa0** [comment]
> _since resource_cml_runner does handle a b64 encoded startup_script (whether it comes from JSON or HCL), but resource_machine does not._

Touché! Sorry for the inconsistent API, #91's purpose is exactly modifying `resource_cml_runner` to behave like `resource_machine` and take raw scripts.

> `iterative/tpi` already works as-is whether the user is using the HCL `render_template` or the JSON `render_json` to generate the terraform config. `iterative/tpi` just expects the user to pass their `startup_script` as a (multiline) string, and either dumps the string directly as JSON, or adds the heredoc wrapper in the templated HCL.

Excellent! I overlooked [`render_json`](https://github.com/iterative/tpi/blob/f9fbc1ccbeb053eaad3b1f4d4177277c0c1bfebf/tpi/__init__.py#L102-L111) 🤦🏼

**Comment by 0x2b3bfa0** [comment]
Closing in favor of #91
