### ISSUE TITLE
More diagnostic messages are needed

### ISSUE THREAD

**Issue by dmpetrov** [iterative/terraform-provider-iterative#17]
It is not easy to understand what happened if my job stocked. It would be great to have more logs.

**Comment by 0x2b3bfa0** [comment]
Related to https://github.com/iterative/terraform-provider-iterative/pull/70

**Comment by 0x2b3bfa0** [comment]
What else can we do to display insightful diagnositc messages on failure?

**Comment by 0x2b3bfa0** [comment]
Opposite of #154?

**Comment by 0x2b3bfa0** [comment]
I guess that this issue can be safely closed. The new `iterative_task` resource already provides useful logs, and the legacy `iterative_cml_runner` resource is considerably more verbose than in November 2020. See https://github.com/iterative/cml/issues/938 for further action points.
