### ISSUE TITLE
Upgrade CUDA on machine images to 11+

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#174]
### Follow-up of https://github.com/iterative/cml/issues/654

Machine images are still using CUDA 10, but we also offer support for CUDA 11 on container images. It would be awesome if we could upgrade it on our machine images without breaking backwards compatibility.

Related to #146

**Comment by DavidGOrtega** [comment]
Ideally users would have to use images in their workflow. And never use the bare metal instance, anyway we could have AMIs with CUDA upgrade

**Comment by 0x2b3bfa0** [comment]
Please refer to https://github.com/iterative/cml/issues/654 for context: the CUDA version on the bare metal instance affects the version of the libraries exposed to the container through the NVIDIA runtime.

**Comment by casperdcl** [comment]
Odd. I thought the entire point is the bare metal only needs NVIDIA runtime drivers but not CUDA libraries. The container contains CUDA libraries which require the bare metal to have compatible drivers.

**Comment by 0x2b3bfa0** [comment]
> Our custom machine images [don't](https://github.com/iterative/terraform-provider-iterative/blob/2673108a43d318b5e6c86b5ea8d678764e0db78f/cml/setup.sh) add any value over [NVIDIA NGC](https://docs.nvidia.com/ngc/ngc-deploy-public-cloud) other than Node.js. Given that [cml#825](https://github.com/iterative/cml/issues/825) removes the dependency on Node.js, maybe we should consider deprecating our machine images in favor of the NVIDIA ones. :thinking_face:
> 
> ### `aws`
> https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-aws/#ami-overview
> `NVIDIA Deep Learning AMI 20.03.1`
> 
> ### `az`
> https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-azure/#overview
> `NVIDIA-GPU-Cloud-Image-2020.03.24`
> 
> ### `gcp`
> https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-gcp/index.html#overview
> `nvidia-gpu-cloud-image-20200324`
> 
> ### `k8s`
> https://docs.nvidia.com/ngc/ngc-deploy-public-cloud/ngc-deploy-containers/index.html

**Comment by 0x2b3bfa0** [comment]
`libcusolver.so.11` is, in fact, present in out container images; I was probably wrong with https://github.com/iterative/cml/issues/654
