### ISSUE TITLE
Machine Transparent Spot Instances

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#176]
Dvc executors will need the machine resource to be able to have this feature.
This is a discussion thread.

## Proposal

 - Reuse storage?
 - DVC 
     - https://github.com/iterative/dvc/pull/6332 
     - https://github.com/iterative/dvc.org/pull/2587/

**Comment by 0x2b3bfa0** [comment]
Machine-level spot instance transparent migration doesn't seem like an easy feat. While we can use [`docker checkpoint`](https://docs.docker.com/engine/reference/commandline/checkpoint) for containers or vendor-specific solutions for machines, none of these methods support GPU state checkpointing:

- https://github.com/checkpoint-restore/criu/issues/534
- https://github.com/checkpoint-restore/criu/issues/384
- https://github.com/NVIDIA/nvidia-container-runtime/issues/44
- https://arxiv.org/pdf/2008.10596.pdf
- https://on-demand.gputechconf.com/gtc/2016/presentation/s6429-akira-nukada-transparen-checkpoint-restart-technology-cuda-applications.pdf

We can help with storage, be either through DVC or independently, but can't migrate machines without interrupting the training process and jobs still need to be checkpoint-aware.

**Comment by 0x2b3bfa0** [comment]
Closed with #237
