### ISSUE TITLE
json support

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#180]
Terraform should support `.json` in addition to `.tf` in case the user prefers a more widely-used format. Can we confirm/document this?

**Comment by pmrowla** [comment]
see: https://www.terraform.io/docs/language/syntax/json.html

**Comment by 0x2b3bfa0** [comment]
We **do** support the [`.json.tf` configuration syntax](https://www.terraform.io/docs/language/syntax/json.html) natively.

**Comment by 0x2b3bfa0** [comment]
@pmrowla, you're blazingly fast! 🚀

**Comment by casperdcl** [comment]
we just had a meeting :)

**Comment by 0x2b3bfa0** [comment]
Closing as resolved; we shouldn't need to _invent here_ the linked documentation.

**Comment by casperdcl** [comment]
the [readme](https://github.com/iterative/terraform-provider-iterative/#readme) misleadingly only mentions `main.tf`. At the least that should be changed.

**Comment by 0x2b3bfa0** [comment]
@casperdcl, should we provide `.tf.json` examples for all our resources?

Given the current status of the readme file (and the API it describes), I would just mention that we also support the JSON syntax as any other provider.

**Comment by 0x2b3bfa0** [comment]
Just to clarify: this is a Terraform feature, not a provider-specific feature.

**Comment by 0x2b3bfa0** [comment]
Historical note: if looking for examples, check https://github.com/iterative/terraform-provider-iterative/issues/168#issuecomment-911349951
