### ISSUE TITLE
Smoke tests

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#202]
A GH workflow doing some TPI smoke tests to avoid manual tests

**Comment by 0x2b3bfa0** [comment]
Closed with #237 for the code behind the `iterative_task` resource. Feel free to open a different issue for `iterative_machine` or for a more general test at the HCL level.

**Comment by 0x2b3bfa0** [comment]
Reopened by @DavidGOrtega to add end–to–end tests complementing [`task_test.go`](https://github.com/iterative/terraform-provider-iterative/blob/082cde917f5e0be78edbde32ca6fab332537f67c/task/task_test.go)

**Comment by 0x2b3bfa0** [comment]
Now that smoke tests were fixed, I wonder if we should close this issue.

**Comment by casperdcl** [comment]
whacking zombie moles
