### ISSUE TITLE
📚 Epic: Advance code sync

### ISSUE THREAD

**Issue by dmpetrov** [iterative/terraform-provider-iterative#212]
In basic scenarios, a simple copy of train.py might be enough. However, in more realistic ones the entire Git workspace needs to be transferred - `dvc exp` can create snapshots like this. This tool (or idea) should be reused for proper workspace copy.

**Comment by DavidGOrtega** [comment]
I was assuming to copy current folder or clone repo like a runner does. 
This first might be more convenient that the later since you can sync non yet committed code

**Comment by 0x2b3bfa0** [comment]
Closed with #237
