### ISSUE TITLE
Prevent very long-running instances

### ISSUE THREAD

**Issue by jbencook** [iterative/terraform-provider-iterative#227]
We have TPI instances that have been up for a month+ -- way too long. We need to prevent this from happening.

Some possible solutions:

* Alerting after 24 hours of uptime (also see [Cloud Custodian](https://github.com/cloud-custodian/cloud-custodian))
* Auto-terminating TPI instances after the executor finishes/fails
* Giving users a list view of all TPI jobs/instances

Accidental long-running instances are one potential cause of iterative/cml#675.

**Comment by 0x2b3bfa0** [comment]
🔔 @iterative/cml, #237 introduces task timeouts. Feel free to reopen if you believe that this issue can be solved in a better way.
