### ISSUE TITLE
Proto - Remote executor: instance recovery

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#230]
On startup:
 - Checks the remote tfstate:
    - If we have the job running and the id is diff of what we have another executor must have been launched. Die.

On execution:
  - Update cloud state with logs 
 
On termination:
- Job completed:
  - Updates cloud state with logs
  - Updates remote state logs with machine logs and completion time and destroying instance details
  - updates remote state with ```completed```
 
- Detects SIGTERM or cloud spot termination:
   - launches a new Instance
   - updates the remote state logs with termination and new request logs
   - updates the remote state with ```provisioning```

## Acceptance tests

WIP

**Comment by jbencook** [comment]
We can safely skip logs for answering the question about whether we can support spot recovery in the Terraform client approach.

At a high level, the acceptance tests for this should be something like:

1. The instance terminates during task execution. A new instance spins up and completes the task.
2. A user requests an instance with a spot price that's too low. After waiting for an instance to become available, the instance spins up and the task is executed.
3. The task fails with a non-zero exit code. The instance is terminated or at least stops.

**Comment by 0x2b3bfa0** [comment]
Closed with #237
