### ISSUE TITLE
Using a custom AMI doesn't work

### ISSUE THREAD

**Issue by jamt9000** [iterative/terraform-provider-iterative#231]
The documentation refers to an `image` field but setting this field in the `iterative_cml_runner` provider gives an error

```
│ Error: Computed attribute cannot be set
│
│   with iterative_cml_runner.runner,
│   on main.tf line 32, in resource "iterative_cml_runner" "runner":
│   32:   image = "helloworld"
```

Since it is specified as `Computed: true`

https://github.com/iterative/terraform-provider-iterative/blob/82d1b6047b728084d8b235e69f181ae608309db8/iterative/resource_runner.go#L92

Setting it in `iterative_machine` provider seems to work, but then I don't see how to do that in the cml-runner script which is using `iterative_cml_runner` here:
 https://github.com/iterative/cml/blob/4fd2d8b866aed63dd15a5073f9dfafdb51c13544/src/terraform.js#L88

**Comment by 0x2b3bfa0** [comment]
Allowing custom images for the `iterative_cml_runner` resource looks like a shoot in the foot. We're relying on a specific image to perform some operations, and if users specify an arbitrary image, things may (and will) break.

Nevertheless, this is easier to fix with code than documentation: we can allow to override teh default image but consider it unspecified behavior.
