### ISSUE TITLE
Document test Kubernetes cluster creation

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#257]
# Follow–up: https://github.com/iterative/terraform-provider-iterative/pull/237#discussion_r755000380 & https://github.com/iterative/terraform-provider-iterative/pull/189#issuecomment-916911104

https://github.com/iterative/terraform-provider-iterative/blob/813894ef029930bb9b10d725f2f6b13f27ece4da/.github/workflows/smoke.yml#L22-L49

https://github.com/iterative/terraform-provider-iterative/blob/813894ef029930bb9b10d725f2f6b13f27ece4da/.github/workflows/smoke.yml#L98-L107

## Setting up Azure Kubernetes Service ([Notion](https://www.notion.so/iterative/Setting-up-Azure-Kubernetes-Service-c20e523be5484ec29a2c2ad5fcc76be2))

> ### Installing the Azure command-line interface tool
> 
> First of all, we need to install the `az` tool following the official documentation on the Microsoft documentation portal: [https://docs.microsoft.com/en-us/cli/azure/install-azure-cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)
> 
> ### Enabling experimental features
> 
> In order to automatically provision GPU nodes for our cluster, we'll also need to enable the following experimental features through the `aks-preview` extension:
> 
> ```bash
> az extension add \
>   --name aks-preview
> 
> az provider register \
>   --namespace Microsoft.ContainerService
> 
> az feature register \
>   --namespace Microsoft.ContainerService \
>   --name GPUDedicatedVHDPreview
> ```
> 
> ### Creating a test cluster
> 
> The following commands will create an AKS cluster with a single node, keeping everything into a a new resource group for easier deletion of the resources:
> 
> ```bash
> az group create \
>   --name testKubernetesResourceGroup \
>   --location eastus
> ```
> 
> ```bash
> az aks create \
>   --resource-group testKubernetesResourceGroup \
>   --name testKubernetesCluster \
>   --node-vm-size Standard_NC6 \
>   --node-count 1 \
>   --aks-custom-headers UseGPUDedicatedVHD=true
> ```
> 
> <details><summary><i>Click to reveal a budget-friendly cluster configuration without GPU...</summary>
> 
> ```bash
> az aks create \
>   --resource-group testKubernetesResourceGroup \
>   --name testKubernetesCluster \
>   --node-vm-size Standard_A2_v2 \
>   --node-count 1
> ```
> </details>
> 
> ### Retrieving the credentials
> 
> Azure has some wrappers for Kubernetes authentication and will generate for us the required credentials. The following command will produce a full-fledged `kubeconfig` string that can be directly stored in the `KUBERNETES_CONFIGURATION` secret of your continous integration system of choice:
> 
> ```bash
> az aks get-credentials \
>   --resource-group testKubernetesResourceGroup \
>   --name testKubernetesCluster \
>   --file -
> ```
> 
> > 💡 *If you skip the `--file` option, settings will be saved to your computer's `~/.kube/config` file, that will be automatically used by `kubectl` if you ever need to run any sanity check manually on the cluster.*
> 
> ### Deleting the test cluster
> 
> Once you've finished testing you can run the following command to delete the entire resource group, which includes the cluster and all its nodes:
> 
> ```bash
> az group delete \
>   --name testKubernetesResourceGroup
> ```
> 
> > ⚠️ *Please delete the entire resource group as soon as you finish using the cluster. They are really pricey, and you may end spending a lot of money just on testing. 🔥  💵*

**Comment by 0x2b3bfa0** [comment]
Kubernetes users should already have a working cluster and, to my mind, documenting the cluster configuration process seems a bit out of scope.

I wrote the documentation above just for testing this provider on [AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/#overview), but external contributors might prefer to use [EKS](https://aws.amazon.com/eks), [GKE](https://cloud.google.com/kubernetes-engine) or on–premises solutions.

**Comment by 0x2b3bfa0** [comment]
@casperdcl, where (if any) would you like to publish this information?

**Comment by casperdcl** [comment]
I'd suggest a new file under https://github.com/iterative/terraform-provider-iterative/tree/master/docs/guides.
