### ISSUE TITLE
`task` recovering with tricked names is launching new tasks 

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#298]
![image](https://user-images.githubusercontent.com/414967/143418439-91636c66-2782-4552-b9f1-71a3a49d5fc6.png)

```tf
terraform {
  required_providers {
    iterative = {
      source = "iterative/iterative",
    }
  }
}

provider "iterative" {}

resource "iterative_task" "task1" {
  cloud     = "aws"
  name      = "fashion-mnist-1503063863"
  directory = "./gh"
  script = ""
}

resource "iterative_task" "task2" {
  cloud     = "aws"
  name      = "fashion-mnist-gl-416155410"
  directory = "./gl"
  script = ""
}

resource "iterative_task" "task3" {
  cloud     = "aws"
  name      = "fashion-mnist-bb-119"
  directory = "./bb"
  script = ""
}

```

Expecting to have the trickery 
```go
if identifier =~ tpi-*-valid-hash
  return identifier
else
  return normalize(identifier)
```
but I did not find it in the source code? 🤔

**Comment by 0x2b3bfa0** [comment]
### Source code
https://github.com/iterative/terraform-provider-iterative/blob/1c66156d32935578b583b8006723a65f301a2a8e/task/common/identifier.go#L16-L27

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, this is really weird. I must have done “something wrong somewhere” but still can't figure what.

**Comment by DavidGOrtega** [comment]
As far as I can see you expect me to set the full bucket name 
```js
(`?s)^tpi-([a-z0-9]+(?:[a-z0-9-]*[a-z0-9])?)-([a-z0-9]+)-([a-z0-9]+)$`
```

**Comment by 0x2b3bfa0** [comment]
Yes, although you should also be able to use the original name as previously.

**Comment by 0x2b3bfa0** [comment]
#304 proves this is [a layer–8 error](https://en.wikipedia.org/wiki/Layer_8) and, as usual, it was caused by underscore blindness.

```go
Identifier("fashion-mnist-gl-416155410").Long() == "tpi-fashion-mnist-gl-416155410-1b5rm7q-1lrey8c"
Identifier("fashion_mnist-gl-416155410").Long() == "tpi-fashion-mnist-gl-416155410-lmz6oc-1728jrj"
```

[Try it yourself in the Go Playground](https://go.dev/play/p/2OwqKx9GnpD)

![images](https://user-images.githubusercontent.com/11387611/143465795-571c0f77-79cf-461a-a5a1-de2a1d830b17.jpg)

**Comment by DavidGOrtega** [comment]
> it was caused by underscore blindness.

I knew it when I tried but I understood when you explained to me that the magic was not needed to remember if the name was written with underscore or not not that the tpi is now able to relate buckets names with user identifiers.
So not blindness but being delusional

**Comment by 0x2b3bfa0** [comment]
🤦🏼‍♂️ Oops! No, it wouldn't be able to infer the identifier from a fragment of it, only from the full (long) identifier in the form: `tpi-human-friendly-firsthash-secondhash`
