### ISSUE TITLE
`task` make script field optional

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#305]
In order to be able to recover the task, I need to setup `script` field as

```tf
script = ""
```

Looks a bit strange that we need to setup it with an empty string.

**Comment by 0x2b3bfa0** [comment]
The question is: should we? What would a task do with an empty script?

**Comment by DavidGOrtega** [comment]
we use this pattern to recover the tasks and its silly to set an empty `script` asking for it and allowing it empty is the same but with the hassle of having to write it empty.

**Comment by casperdcl** [comment]
related #300 / #307

**Comment by 0x2b3bfa0** [comment]
Still not sure about making script optional. 🤷🏼‍♂️ If we have to implement this, adding `#!/bin/sh\nsleep infinity` as the default value should be enough.

**Comment by dacbd** [comment]
Is this still valid / did we decide on optional or default of `sleep`?

**Comment by 0x2b3bfa0** [comment]
This issue has been stale for a while and it doesn't look like there is a valid use case for this anymore. @iterative/cml, feel free to reopen if it's needed for any of our documented workflows.

**Comment by casperdcl** [comment]
​Could document

```
script = <-END
  #!/bin/bash
  ... >> .ssh/authorized_keys
  sleep inf
END
```

for testboxes?

**Comment by 0x2b3bfa0** [comment]
Same as https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/getting-started#debugging?
