### ISSUE TITLE
`task` destroy, need of being able to specify output folder

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#307]
If I launch a cluster of tasks in the same workdir but different env vars or script I would like to be able to recover all the execution in different folders. The problem right now is that `directory` is used in the initial sync and in the final `output`. 
We need to be able to specify `directoryOutput` aligned with `directory` by default to avoid this outputs to be overwritten

```tf
resource "iterative_task" "task1" {
  cloud     = "aws"
  machine   = "t2.micro"
  spot      = 0
  name      = "task1"
  directory = "."
  region    = "us-west"

  script = <<-END
    #!/bin/bash
    echo 'task1' >> report.md
  END
}

resource "iterative_task" "task2" {
  cloud     = "aws"
  machine   = "t2.micro"
  spot      = 0
  name      = "task2"
  directory = "."
  region    = "us-west"

  script = <<-END
    #!/bin/bash
    echo 'task2' >> report.md
  END
}
```

If I destroy the example above I have just only a mess in current folder we might want 

```tf
resource "iterative_task" "task1" {
  cloud     = "aws"
  machine   = "t2.micro"
  spot      = 0
  name      = "task1"
  directory = "."
  output = "./task1"
  region    = "us-west"

  script = <<-END
    #!/bin/bash
    echo 'task1' >> report.md
  END
}

resource "iterative_task" "task2" {
  cloud     = "aws"
  machine   = "t2.micro"
  spot      = 0
  name      = "task2"
  directory = "."
  output = "./task2"
  region    = "us-west"

  script = <<-END
    #!/bin/bash
    echo 'task2' >> report.md
  END
}
```

note the `output` property

**Comment by 0x2b3bfa0** [comment]
This probably belongs to an epic about parallel training. With the current behavior, users can solve that by writing the result of each machine to a different path:

```hcl
resource "iterative_task" "task" {
  name        = "example"
  cloud       = "aws"
  parallelism = 4

  script = <<-END
    #!/bin/bash
    date >> result-$(uuidgen)
  END
}
```

**Comment by 0x2b3bfa0** [comment]
Machines aren't aware of their “slot” and have no means of knowing if they're resuming an interrupted tast or starting a new one. Without implementing some sort of leader election and task splitting mechanism, there won't be an 1:1 mapping between `parallelism` and the number of outputs.

**Comment by DavidGOrtega** [comment]
Im not speaking about training in parallel, just launch the same task with different parameters within the same terraform file

**Comment by DavidGOrtega** [comment]
Im updating with a terraform example

**Comment by 0x2b3bfa0** [comment]
Thanks for the clarification! 🙏🏼

Still, it looks like [my first reply](https://github.com/iterative/terraform-provider-iterative/issues/307#issuecomment-979303706) is relevant: you can avoid overwriting artifacts by naming them differently.

**Comment by 0x2b3bfa0** [comment]
We should probably consider having separate directories for input and output:

### With attributes

```hcl
resource "iterative_task" "task" {
  name        = "example"
  cloud       = "aws"

  input_directory  = "."
  output_directory = "./output"

  script = <<-END
    #!/bin/bash
    date >> result
  END
}
```

### With a block

```hcl
resource "iterative_task" "task" {
  name        = "example"
  cloud       = "aws"

  script = <<-END
    #!/bin/bash
    date >> result
  END

  directories {
    input  = "."
    output = "./output"
  }
}
```

**Comment by DavidGOrtega** [comment]
```tf
directories {
    input  = "."
    output = "./output"
  }
```
Love this idea.
As I said In other issues I can recover a bunch of tasks and change the `directory` do `apply` and then the output folder will be the one I gave. However to make it work I have to first remove the tfstate and then the `apply` and then `destroy`... not very user friendly

**Comment by 0x2b3bfa0** [comment]
Regarding user experience, we may want to set `ForceNew: true` for the `directory` attribute in the schema, so it can be updated locally.

https://github.com/iterative/terraform-provider-iterative/blob/fa9c7f8f833c9fc74f11d637f42f03e5866b8e26/iterative/resource_task.go#L105-L110

**Comment by DavidGOrtega** [comment]
I have picked this @0x2b3bfa0
