### ISSUE TITLE
Remove useless runner waiting code

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#315]
[Circa September 2021](https://github.com/github/docs/pull/9307), GitHub modified the runner routing logic so jobs don't fail anymore when there is no runner available with the required labels.

This eliminates the need for a substantial amount of workarounds in out code, and we should probably consider removing them.

### https://github.com/github/docs/pull/9307

> * _If GitHub finds an online and idle runner at a certain level that matches the job's `runs-on` labels, the job is then assigned and sent to the runner._
> * _If GitHub doesn't find an online and idle runner at any level, the job is queued to all levels and waits for a matching runner from any level to come online and pick up the job._
> * _If the job remains queued for more than 24 hours, the job will fail._
>
> (From [“routing precedence for self-hosted runners”](https://docs.github.com/en/enterprise-cloud@latest/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#routing-precedence-for-self-hosted-runners) on the official GitHub documentation)

### https://github.com/actions-runner-controller/actions-runner-controller/pull/909

> _This is a deprecated feature for GitHub Cloud as "registration-only" runners are no longer needed due to GitHub changing their runner [routing logic](https://docs.github.com/en/enterprise-cloud@latest/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#routing-precedence-for-self-hosted-runners) to no longer fail a workflow run if it targets a runner label that there are no registered runners for._
>
> (From [“autoscaling to/from 0”](https://github.com/actions-runner-controller/actions-runner-controller#autoscaling-tofrom-0) on the [actions-runner-controller](https://github.com/actions-runner-controller/actions-runner-controller) documentation, linked from [the official documentation](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#recommended-autoscaling-solutions))

## Code

https://github.com/iterative/terraform-provider-iterative/blob/fa9c7f8f833c9fc74f11d637f42f03e5866b8e26/iterative/resource_runner.go#L224-L262

https://github.com/iterative/terraform-provider-iterative/blob/fa9c7f8f833c9fc74f11d637f42f03e5866b8e26/iterative/utils/runner.go#L1-L40

https://github.com/iterative/terraform-provider-iterative/blob/fa9c7f8f833c9fc74f11d637f42f03e5866b8e26/iterative/resource_machine.go#L278-L289

**Comment by DavidGOrtega** [comment]
The await code here has nothing to be with the ability of GH of continue if no runner is present.
The await code is done to check if if the runner can register successfully and be able to log the reason why is not properly registering or being launched
