### ISSUE TITLE
`task` status field is not consistent enough

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#319]
Im pretending to use the task status to do a check in the ci however does not seems effective enough, the reason is that seems that terminated status is present in the very first run?!!

```sh
if terraform show --json | grep "terminated Client.UserInitiatedShutdown"; then
  # this will run even in the first CI run
  echo 'Destroying...'
  terraform destroy --auto-approve -var "name=${NAME}"

  cml send-github-check --token=$GITHUB_TOKEN --conclusion=success --title='Training Model' report.md
  cml pr --md output/* >> report.md
  cml send-comment --update report.md
  cml send-comment --update --pr --commit-sha HEAD report.md
else
  echo 'Creating report...'
  echo 'training model...' > report.md
  cml send-github-check --token=$GITHUB_TOKEN --conclusion=neutral --title='Training Model' report.md
fi
```

We need:
 - Consistent ONE word statuses across the cloud vendors:
    - running
    - terminated
    - failed

This is the status in AWS (a bit weird I might say):

```json
"status":{
"running":38,
"terminated Client.UserInitiatedShutdown: User initiated shutdown":6
},
```

**Comment by 0x2b3bfa0** [comment]
* `running` is consistent across every provider
* “not running” isn't consistent, but can be defined as `total - runnning` on every provider

Failure/success is not currently part of `status` but rather of `logs`, although it would be nice to have it in the same place.

**Comment by 0x2b3bfa0** [comment]
Just to confirm: were your _really_ running 40 machines?

**Comment by DavidGOrtega** [comment]
Ok we have an issue, seems that they are not terminated

![image](https://user-images.githubusercontent.com/414967/144128586-a0b2b21d-c1d2-4561-9a8e-b4057331e44c.png)

**Comment by DavidGOrtega** [comment]
the bill for this month is going to be monumental

**Comment by DavidGOrtega** [comment]
running: number does not means anything in the task concept

**Comment by DavidGOrtega** [comment]
As I said `running` and the number of instances that the user have in play is not relevant to the `task` entity. I need to know the status of the script execution. `completed`, `running`, `migrating` or `failed`  and then maybe we can think in how to represent the whole tasks data if we wish but status field in the task should just represent the current status of the task

**Comment by 0x2b3bfa0** [comment]
We can use `ExecStop=` for reporting the exit status and then `ExecStopPost=` for scaling down the instances.
