### ISSUE TITLE
`task` is not being totally stopped if not destroyed

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#320]
Seems that tasks can come back after task completion if not destroyed.
I had an enormous amount of scale groups with 1 instance that were in fact terminated tasks but not destroyed

**Comment by DavidGOrtega** [comment]
Maybe we should not scale down the group and we should destroy it entirely after the task completion @iterative/cml

**Comment by 0x2b3bfa0** [comment]
Fixed with #318, or that's what we believe.

**Comment by 0x2b3bfa0** [comment]
Fixed with #318, or that's what we believe.

**Comment by 0x2b3bfa0** [comment]
> _Maybe we should not scale down the group and we should destroy it entirely after the task completion._

We definitely could destroy the group instead, but:
1. Destroying is a heavier operation than scaling down, and potentially more prone to errors.
2. It would be harder to scale it up again if we needed to, for example when users update/relaunch a task.
3. We're losing the task consistency.
