### ISSUE TITLE
Error: exceeded max wait time for InstanceTerminated waiter

### ISSUE THREAD

**Issue by MKhalusova** [iterative/terraform-provider-iterative#331]

**Comment by MKhalusova** [comment]
terraform apply gets stuck destroying a resource and eventually fails with Error: exceeded max wait time for InstanceTerminated waiter

**Comment by 0x2b3bfa0** [comment]
Do instances remain active in the cloud after the error message?

Can you please run `terraform refresh && terraform show` and post the output?

**Comment by MKhalusova** [comment]
It seems that there were no EC2 instances with that id, but there was a security group with the id. 

After it finished with the error, I tried terraform apply and it worked.

**Comment by DavidGOrtega** [comment]
duplicated of #306

**Comment by casperdcl** [comment]
actually in #306 the original error was `Error: corrupted on transfer: sizes differ 310 vs 311`. Is that really the same as this?

**Comment by dacbd** [comment]
Is this still an error? Do we know the `main.tf` / order of operations to reproduce? 🧹

**Comment by 0x2b3bfa0** [comment]
Fixed on #486
