### ISSUE TITLE
`task` is not syncing the workspace

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#338]
Has already happened to me twice in the last 24 hours trials. Of course the file exists, its running in my repo.

```
Dec 21 21:29:04 tpi000001 tpi-task[7687]: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Dec 21 21:29:04 tpi000001 tpi-task[7708]: python3: can't open file 'train.py': [Errno 2] No such file or directory
Dec 21 21:29:04 tpi000001 systemd[1]: tpi-task.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 21 21:29:04 tpi000001 tpi-task-shutdown[7713]: 2021/12/21 21:29:04 [INFO] Stopping task tpi-gh-1608701046-2x7kqf8y-57yhbgmz...
"
```

**Comment by 0x2b3bfa0** [comment]
Might be due to eventual consistency? 🤔

**Comment by DavidGOrtega** [comment]
> Might be due to eventual consistency? 🤔

You mean transient? Maybe... as far as I can see the task is syncing the data previously so I wonder if somehow clone is not mislead

**Comment by 0x2b3bfa0** [comment]
Can you see the files in the Azure Portal?

**Comment by DavidGOrtega** [comment]
> Can you see the files in the Azure Portal?

🤦 sorry late, I removed the task. I will look after this

**Comment by DavidGOrtega** [comment]
My bad. Installing my tpi I was changing my workspace
