### ISSUE TITLE
Error: output directory is not empty!

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#358]
following #340:

```hcl
resource "iterative_task" "task" {
  ...
  workdir { input = "${path.root}/shared" }
}
```

results in `Error: output directory ./shared is not empty!`

**Comment by 0x2b3bfa0** [comment]
This behavior seems intentional and especially counterintuitive.

https://github.com/iterative/terraform-provider-iterative/blob/be9e0cde944cd6d2959bec2f70da6cb40cc8cf97/iterative/resource_task.go#L287-L289

**Comment by casperdcl** [comment]
Yes there's nothing wrong with effectively `if not output: output = input` but the problem is subsequently insisting that `output.ls() == []`

**Comment by DavidGOrtega** [comment]
Im not following this.
If the output dir exists and is not empty it fails to not overwrite it (and to not upload it also at start).
Whats the issue? what's counterintuitive?

**Comment by 0x2b3bfa0** [comment]
🤔 If `output` has to be empty, it would make more sense to remove the code mentioned on https://github.com/iterative/terraform-provider-iterative/issues/358#issuecomment-1009234185.

**Comment by 0x2b3bfa0** [comment]
Using the same directory for input and output is known to produce all kinds of issues. Should we support this mode of operation?

**Comment by DavidGOrtega** [comment]
I have created a fix, the order was not right. Now sets the output as the input if not defined and verifies the output to be OK if defined
