### ISSUE TITLE
handle `task` workdir file deletions

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#360]
Delete files from bucket when deleted on remote instance (so `terraform destroy` doesn't download them)

**Comment by 0x2b3bfa0** [comment]
Easy for machines: https://github.com/iterative/terraform-provider-iterative/blob/2673108a43d318b5e6c86b5ea8d678764e0db78f/task/common/machine/storage.go#L102

**Comment by 0x2b3bfa0** [comment]
For Kubernetes, it's a bit more involved, though.

**Comment by 0x2b3bfa0** [comment]
I actually was thinking of <kbd>object storage</kbd> to <kbd>local</kbd> synchronization, not of <kbd>machine</kbd> to <kbd>object storage</kbd> synchronization. What you asked is as easy as using `rclone sync` on machines.
