### ISSUE TITLE
`task`: skip existing files on download

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#361]
Don't download files if size/mode time/checksum is the same.

**Comment by 0x2b3bfa0** [comment]
Similarly to https://github.com/iterative/terraform-provider-iterative/issues/360#issuecomment-1010198069, it should be easily feasible for machines, but not that much for Kubernetes.

**Comment by DavidGOrtega** [comment]
> Similarly to [#360 (comment)](https://github.com/iterative/terraform-provider-iterative/issues/360#issuecomment-1010198069), it should be easily feasible for machines, but not that much for Kubernetes.

Lets do it at least for machines.

**Comment by 0x2b3bfa0** [comment]
This is a core feature of `rclone` and already implemented unless proven otherwise.

```hcl
terraform {
  required_providers {
    iterative = {
      source = "github.com/iterative/iterative"
    }
  }
}

provider "iterative" {}

resource "iterative_task" "example" {
  cloud   = "aws"
  machine = "m"

  script = <<-END
    #!/bin/sh
    fallocate --length 1G file
  END

  storage {
    workdir = "."
    output  = "file"
  }
}
```
