### ISSUE TITLE
`task` rclone Config file not found

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#373]
Found within the logs 
```sh
NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
```

**Comment by 0x2b3bfa0** [comment]
<kbd>wontfix</kbd> perhaps? 🤔 [rclone/fs/config/config.go:359](https://github.com/rclone/rclone/blob/b783f09fc6961e82f0bfb9dff2126c24dae891c9/fs/config/config.go#L359)

**Comment by 0x2b3bfa0** [comment]
Happening because the `ExecStop` command includes a last call to `rclone` which also gets logged:

https://github.com/iterative/terraform-provider-iterative/blob/610c4492084a59400c73f71f951ec0a8a4f4a836/task/common/machine/script.go#L64

Better to have it than to miss possible errors?

**Comment by DavidGOrtega** [comment]
Its not a very good logs I might say. Users reviewing their logs will scratch their heads

**Comment by 0x2b3bfa0** [comment]
Let's keep it open. I'll eventually try to figure out if we can suppress it.
