### ISSUE TITLE
Generate random suffixes for `task` identifiers

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#379]
Identifiers have some undesirable properties that may deteriorate the user experience:

#### Determinism

Identifiers appear to be random, but they are deterministic: setting `name = "example"` will always create resources named `tpi-example-20jeru6v-16rrmkup` instead of generating new random suffixes for every run.

This behavior may confuse users, and breaks all the documentation examples where object storage names have to be hlobally unique.

#### Normalization

Identifiers are substantially different to names, and comply with the naming constraints of the most restrictive cloud providers. Unless proven otherwise, this is a desirable property; we shouldn't make users responsible of knowing all the naming conventions of their cloud provider in order to use this resource.

### Related code
https://github.com/iterative/terraform-provider-iterative/blob/610c4492084a59400c73f71f951ec0a8a4f4a836/task/common/identifier.go#L1-L67

https://github.com/iterative/terraform-provider-iterative/blob/610c4492084a59400c73f71f951ec0a8a4f4a836/task/common/identifier_test.go#L1-L47

**Comment by dmpetrov** [comment]
It might be better to copy-past or summarize the internal discussions to public issues.

**Comment by 0x2b3bfa0** [comment]
🙈 Sorry!

**Comment by 0x2b3bfa0** [comment]
### Solutions

#### Terraform

Generating a random identifier for every task is probably the most elegant and idiomatic approach, but:

1. Users will be responsible of keeping [state](https://www.terraform.io/language/state) in a safe place (e.g. a `terraform.tfstate` file or a remote backend) and treat it with the same considerations as any production–grade `terraform` state file.
2. State should remain excluded from version control, because it [contains sensitive information](https://stackoverflow.com/a/41482391/4654476): https://github.com/hashicorp/terraform/issues/13891

#### Standalone

Again, random identifiers would be the most elegant solution. Unlike in the `terraform` scenario, users wouldn't need to be responsible of state, because there would be a `list` method to retrieve a list of tasks from the cloud API.
