### ISSUE TITLE
EPIC `task` Better logs

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#387]
Almost all the test have coincided about the lack of easiness of debugging the task using the logs.
I propose to log what we store in logs and events using the terraform CLI during refresh using [logrus](https://github.com/Sirupsen/logrus). With it we should be able later on to add logging capabilities using heredoc and [hooks](https://github.com/Sirupsen/logrus#hooks)

- [ ] #392
- [ ] #393
- [x] #398
- [x] Depends on #399

**Comment by casperdcl** [comment]
Depends on #399

**Comment by casperdcl** [comment]
closing as outstanding issues tracked in #391
