### ISSUE TITLE
`task` CML 🍬 Autogeneration of the name under the CI environment

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#390]
Naming under CI environment should be automatically done based on the CI using the following conventions

### Gitlab
```sh
tpi-$CI_PIPELINE_ID
```

### Github
```sh
tpi-$GITHUB_RUN_ID
```

### Bitbucket
```sh
tpi-$BITBUCKET_STEP_TRIGGERER_UUID
```

**Comment by 0x2b3bfa0** [comment]
Too much sugar to my taste, but... 🤷🏼‍♂️ 

Related to #379

**Comment by DavidGOrtega** [comment]
Its a good compromise for UX, that way they can also change the SCM without hesitation, not having to know how it should be named. In any case they can setup the name as always.
