### ISSUE TITLE
EPIC `task` internal iter 2

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#391]
## p1

- [x] #388
- [x] #392
- [x] #414
- [x] #415
- [x] ~document [`TF_LOG_PROVIDER`](https://www.terraform.io/internals/debugging)~ moved to #457

## p2

- [x] #390
- [x] #389
- [x] #379

**Comment by 0x2b3bfa0** [comment]
https://github.com/iterative/terraform-provider-iterative/issues/303 is already part of https://github.com/iterative/terraform-provider-iterative/issues/362

**Comment by casperdcl** [comment]
closing in favour of remaining #389
