### ISSUE TITLE
docs: `task` requirements 1

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#397]
- [ ] where do env vars/credentials in [docs#authentication](https://registry.terraform.io/providers/iterative/iterative/latest/docs#authentication) come from?
- [ ] what local permissions are required? ~e.g. port 22 open?~
- [ ] explain `workdir` better in [docs/resources/task](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task)
- [ ] explain `script` better in [docs/guides/getting-started#defining-a-task](https://registry.terraform.io/providers/iterative/iterative/latest/docs/guides/getting-started#defining-a-task)
    + is it relative to `workdir`?
    + Example of how a Python script can be used (inline shebang & separate file)?
- [ ] clarify what "destroying unused resources" means (i.e. instance terminated on job failure/completion)

**Comment by DavidGOrtega** [comment]
Im missing here the spot instances lifecycle and CI lifecycle

**Comment by casperdcl** [comment]
added to #363
