### ISSUE TITLE
Logging backend

### ISSUE THREAD

**Issue by dmpetrov** [iterative/terraform-provider-iterative#398]
The backend should "stream" logs to cloud storage bucket by default.

**Comment by casperdcl** [comment]
1. Regarding cost of overwriting vs chunking/appending: maybe split based on size (e.g. split every 4MB)?
2. Regarding streaming to external service, maybe return a static URL to the logs so that some other website (studio.iterative.ai, etc) can render said logs

**Comment by 0x2b3bfa0** [comment]
> _Regarding cost of overwriting vs chunking/appending: maybe split based on size (e.g. split every 4MB)?_

It might be a premature optimization, at least for the AWS speed and pricing model, where internal traffic is free and users pay a fixed amount per request. Retrieving a single file requires a single request, while retrieving several files requires several requests; sounds like a [lapalissade](https://en.wikipedia.org/wiki/Lapalissade).

As long as we keep saving logs to object storage, we should probably consider the cost and performance implications of both approaches.

> _Regarding streaming to external service, maybe return a static URL to the logs so that some other website (studio.iterative.ai, etc) can render said logs_

Sounds convenient, and also a bit scary if done wrongly.

**Comment by DavidGOrtega** [comment]
> It might be a premature optimization,

I agree, lets mimic CI providers. They do not split the logs in chunks (aside the jobs). I think is because the expectation is to have something that even it could looks like a huge list its still manageable

**Comment by DavidGOrtega** [comment]
We are actually streaming the logs every 5 secs. We do consider that this is already fine for now

**Comment by 0x2b3bfa0** [comment]
> [CI/CD systems] _do not split the logs in chunks (aside the jobs)._

I don't know how the internal logging architecture of GitHub Actions works, but it looks like they store each of the [`steps`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps) separately and then collate them for displaying. 🤷🏼‍♂️ Just an off–topic remark.

> _I think is because the expectation is to have something that even it could looks like a huge list its still manageable._

Yes, generating 6.6 MiB of logs would require printing a line (of 80 characters) per second for a whole day.
