### ISSUE TITLE
Decision: Logging design

### ISSUE THREAD

**Issue by dmpetrov** [iterative/terraform-provider-iterative#399]
See more details in #387

**Comment by 0x2b3bfa0** [comment]
### What should be logged?

With the current implementation, users can already run `terraform refresh && terraform show` to see the following information:

1. [`events`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#events) — cloud–specific orchestrator events (e.g. instance creation and termination)
2. [`logs`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#logs) — standard output/error of the user–specified [`script`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#script) running in the cloud machine
3. [`status`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#status) — status (e.g. running/succeeded/failed) of the mentioned [`script`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#script)

It's equivalent to the list on #392 except for the following missing items, which are broad enough[^broad] to deserve separate issues:

4. Price information for all the launched spot instances
5. Data synchronization status or progress
6. Environment setup status or logs

Additionally, the current implementation produces internal [debug logs](https://www.terraform.io/plugin/sdkv2/debugging#log-based-debugging) during the [apply](https://www.terraform.io/cli/commands/apply)/[refresh](https://www.terraform.io/cli/commands/refresh)/[destroy](https://www.terraform.io/cli/commands/destroy) operations.

#### Questions
* **Which of these logs are in scope for [#387](https://github.com/iterative/terraform-provider-iterative/issues/387)/[#392](https://github.com/iterative/terraform-provider-iterative/issues/392)?**
* **Are 4, 5 and 6 an immediate need?**

### Where should logging occur?

Both #387 and #392 state that [`logrus`](https://github.com/Sirupsen/logrus) should be used to _“store logs and events”_ during the `terraform refresh` operation. This operation runs **locally**, and is not intended to display nor store any kind of logs under normal conditions, as stated in https://github.com/iterative/terraform-provider-iterative/issues/392#issuecomment-1039761743.

On the other hand, @DavidGOrtega said in today's meeting that [`logrus`](https://github.com/Sirupsen/logrus) could run **remotely** in cloud instances as part of a custom agent[^agent] and be used to save [`logs`](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#logs) to remote backends (e.g. object storage) in real time; this discussion led to the creation of #398.

#### Questions
* **Where should [`logrus`](https://github.com/Sirupsen/logrus) be used; locally, remotely, or both?**
* **If used [locally](https://github.com/iterative/terraform-provider-iterative/blob/f95361238ee1b7948a34ed31ab814a948f400129/task/aws/task.go#L95), what advantages does it provide over [`log`](https://pkg.go.dev/log) from the standard library?**

### Where should logs be stored?

#392 states that [`logrus`](https://github.com/Sirupsen/logrus) should be used to _“store in logs and events within the terraform status[^state] using the terraform CLI during refresh”_

There are some mentions to centralized logging in https://github.com/iterative/terraform-provider-iterative/issues/392#issuecomment-1036109166 and #393, but they don't appear to be related to the topic of #392. 

#### Questions
* **What is the difference between the [current implementation](https://github.com/iterative/terraform-provider-iterative/blob/f95361238ee1b7948a34ed31ab814a948f400129/iterative/resource_task.go#L212-L233) and the proposed changes?**
* **What is the purpose of [`logrus`](https://github.com/Sirupsen/logrus) in this scenario?**

### How should logs be displayed?

As per https://github.com/iterative/terraform-provider-iterative/issues/392#issuecomment-1039761743, the Terraform command–line tool can't display arbitrary information in real time. This open question is optional, and related to an ongoing debate regarding the fitness of Terraform for this use case.

[^broad]: Environment setup — in the DVC definition — is an involved subject, and we haven't tackled it yet; retrieving price information for every spot instance requires performing a fair amount of API trickery **inside the cloud instances**; and data synchronization status requires integration on the client side.

[^agent]: Also known as “executor” in the legacy terminology we used in Q3 2021 during the planning process.
[^state]: Refering to [state](https://www.terraform.io/language/state); precisely, the local state file.

**Comment by dmpetrov** [comment]
> #### Questions
> * **Which of these logs are in scope for [#387](https://github.com/iterative/terraform-provider-iterative/issues/387)/[#392](https://github.com/iterative/terraform-provider-iterative/issues/392)?**
> * **What's the priority for 4, 5 and 6?**

These questions are related to the client-side (TF UI), not logging backend (agent side) #398

> #### Questions
> * **Where should [`logrus`](https://github.com/Sirupsen/logrus) be used; locally, remotely, or both?**

**logrus** (or another library) should be used in the logging backend which runs in a cloud instance. Not locally.

> * **If used locally, what advantages would it provide over [`log`](https://pkg.go.dev/log) from the standard library?**

I personally don't know. I'd try to use a standard one if it's enough.

> * **If used remotely, how does it compare to the current implementation[3](#user-content-fn-currentlogging-c40e5c36f8c7607a3e54c4c1652132ce) and/or official[4](#user-content-fn-agents-c40e5c36f8c7607a3e54c4c1652132ce) log collection agents?**

Is your point that the current implementation is enough?

Why it **might be** not enough:
1. Are we pulling all the events we need: Statuses (script is starting/failed/finished successfully) as well as User's logs?
2. Are we ok to rsync a single log file (it can be 100s of MB) or do we need to "stream" it by small parts? We can actually make it simple in the beginning and sync a whole file.

If we are doing (1) and (2) and properly saving this in object store properly - it might be fine to keep the current approach. My understanding was - something is missing. @DavidGOrtega could you please clarify on this?

**Comment by 0x2b3bfa0** [comment]
> _These questions are related to the client-side (TF UI), not logging backend (agent side) https://github.com/iterative/terraform-provider-iterative/issues/398_

Yes, these questions are mostly related to the client side, because #387 and #392 seem to be focused on the client side. Hence my initial puzzlement.

> _logrus (or another library) should be used in the logging backend which runs in a cloud instance. Not locally._ [...] _I personally don't know. I'd try to use a standard one if it's enough._

I agree. I wonder what's the point of using a “powerful” logging library locally when there is no way of displaying logs during the normal operation of the provider.

> _Is your point that the current implementation is enough?_

Yes, I believe that the current implemetation is enough, until/unless we need a different/better one.

> _Why it might be not enough:_
>
> _1. Are we pulling all the events we need: Statuses (script is starting/failed/finished successfully) as well as User's logs?_
> _2. Are we ok to rsync a single log file (it can be 100s of MB) or do we need to "stream" it by small parts? We can actually make it simple in the beginning and sync a whole file._

1. Yes, unless proven otherwise.
2. Yes. See #398 for future alternatives to pushing a single file.

> _If we are doing (1) and (2) and properly saving this in object store properly - it might be fine to keep the current approach. My understanding was - something is missing. @DavidGOrtega could you please clarify on this?_

Now we are in the same page. 😅 Let's wait for @DavidGOrtega to clarify the scope and motivation of his proposals.

**Comment by DavidGOrtega** [comment]
As I stated the use of logrus at this stage is convenient because its a configurable logger at least more than `log.Println`.

Even if we are not logging in real time right now I would be able to configure my logs with a logging system and for example if running a terraform with a loop file (multiple experiments) one refresh would allow me to see the logs in one place and i a better format.

Also, according to the need of storing the logs in buckets logrus brings many features out-of-the-box:
 - multiple backends lie syslog... 
 - log rolling 

Once the current bash executor is replaced with a proper executor we should be able to log in real time also.
Hopefully this helps to see the benefits of logrus or not

**Comment by casperdcl** [comment]
Summary:

- For default behaviour, no backend/agent changes are needed for now (e.g. remote `logrus` etc. would need user-specified credentials)
- For frontend/UX/formatting we don't have control over `refresh && show` for now
- We should mention `TF_LOG` in docs

**Comment by 0x2b3bfa0** [comment]
> _We should mention `TF_LOG` in docs_

If anything, [`TF_LOG_PROVIDER`](https://www.terraform.io/internals/debugging)

**Comment by casperdcl** [comment]
should we add that to the list in #392 or #391?

**Comment by 0x2b3bfa0** [comment]
🤷🏼‍♂️ 👌🏼
