### ISSUE TITLE
cml: deadlock when running the script for cloning amis

### ISSUE THREAD

**Issue by redouan-rhazouani** [iterative/terraform-provider-iterative#404]
**Description**
Running the script "cml/clone-amis.go" might result in a deadlock.
The deadlock is caused by the go-routines not freeing the WaitGroup after completion.

**To Reproduce**
Just try to run the script.

**Expected behavior**
The deadlock is resolved

**Additional context**
See https://pkg.go.dev/sync#WaitGroup on how to use WaitGroup.

**Comment by redouan-rhazouani** [comment]
Fix: https://github.com/iterative/terraform-provider-iterative/pull/405

**Comment by 0x2b3bfa0** [comment]
Closed with #405
