### ISSUE TITLE
basic docs improvements

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#415]
- basic README upgrade (make USPs more clear)
  + show/explain spot instance recovery lifecycle
- proper repo metadata
- basic registry docs upgrade (see above)
- ~simple flowcharts/diagrams~ moved to #363

**Comment by 0x2b3bfa0** [comment]
![Timeline](https://user-images.githubusercontent.com/11387611/156228458-73294493-6950-4ca8-a22f-0d85f3f45e51.jpg)

**Comment by casperdcl** [comment]
"simple" :see_no_evil:

**Comment by 0x2b3bfa0** [comment]
https://en.wikipedia.org/wiki/Black_Square_(painting)
