### ISSUE TITLE
When machine stops public ip changes

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#44]
It should be accesible through DNS

**Comment by DavidGOrtega** [comment]
Tried to discover that in AWS the fqdn changes with the ip.
The only way to fix this would be use elastic IPs

**Comment by 0x2b3bfa0** [comment]
* Does the public IP change for the same machine once and if it has been restarted?
* How are our machines/runners affected by this issue?

**Comment by DavidGOrtega** [comment]
> Does the public IP change for the same machine once and if it has been restarted?

yes unless you use an elastic ip

**Comment by 0x2b3bfa0** [comment]
If we choose not to implement https://github.com/iterative/terraform-provider-iterative/issues/122, would this issue matter at all?

**Comment by 0x2b3bfa0** [comment]
To be reopened along with #122 if we choose to implement that feature
