### ISSUE TITLE
task: `destroy` hanging yet follow-up `destroy` immediately succeeds

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#462]
Flaky issue (happened in AWS, not sure if cloud-specific); need logs (`TF_LOG_PROVIDER=DEBUG`) to find root cause.

**Comment by 0x2b3bfa0** [comment]
Related/duplicate: https://github.com/iterative/terraform-provider-iterative/issues/437

**Comment by casperdcl** [comment]
This happened in AWS so don't (yet) even know if it's a duplicate

**Comment by DavidGOrtega** [comment]
I was working on this. Is in my batch. 
The scenario that I have to reproduce this is timeout in spot then timeout in destroy.

**Comment by 0x2b3bfa0** [comment]
Taking over this issue after discovering #486. 🙈 Please use #437 for Azure.
