### ISSUE TITLE
task: generic option combinations not working

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#524]
Some useful generic option combinations don't work:

```hcl
resource "iterative_task" ... {
  cloud   = "aws"
  image   = "nvidia"
  spot    = 0

  # willing to change this, need cheapest possible GPU:
  machine = "m+k80"
  region  = "us-east"
  ...
}
```

```
│ Error: operation error Auto Scaling: CreateAutoScalingGroup, https response error StatusCode: 
400, RequestID: 3c6bae3f-56f2-4a27-a0b5-e46b7323ae9b, api error ValidationError:
You must use a valid fully-formed launch template. The instance configuration for this
AWS Marketplace product is not supported. Please see the AWS Marketplace site
for more information about supported instance types, regions, and operating systems.
```

`machine` working:

- `g4dn.xlarge`
- `l+v100`

not working:

- `m+{k80,v100}`
- `l+k80`

**Comment by 0x2b3bfa0** [comment]
> [_File a bug report with them, asking them to make the AMI available for all instance types. It should be in their best interest to allow that._](https://serverfault.com/a/659684/276950)

**Comment by 0x2b3bfa0** [comment]
More specifically, ask NVIDIA to [enable](https://docs.aws.amazon.com/marketplace/latest/userguide/product-submission.html#updating-your-product) those instance types.

**Comment by 0x2b3bfa0** [comment]
![at](https://user-images.githubusercontent.com/11387611/164532080-fc4ade2b-44c9-43d4-af9f-ff32ed903483.png)

**Comment by casperdcl** [comment]
Can we also have:

generic | aws
--:|:--
`s` | `t2.micro`
`s+t4` | `g4dn.xlarge`

along with other cloud equivalents? #328

**Comment by 0x2b3bfa0** [comment]
Action points for #524, i.e. this issue:
* [Ask NVIDIA to allow using their image on those instances](https://github.com/iterative/terraform-provider-iterative/issues/524#issuecomment-1105625151).
* Use [AWS DLAMI](https://docs.aws.amazon.com/dlami/latest/devguide/what-is-dlami.html) instead of NVIDIA NGC when users specify `image = "nvidia"`

**Comment by 0x2b3bfa0** [comment]
> _Can we also have small instances for now (https://github.com/iterative/terraform-provider-iterative/issues/328)?_

Sounds like #328 to me. 🙃 Also known as <kbd>p5-chore-we-actively-ignore</kbd> unless we have a good reason not to. 😈
