### ISSUE TITLE
`task` fix pollution of environment variables for the `tpi-task.service`

### ISSUE THREAD

**Issue by dacbd** [iterative/terraform-provider-iterative#561]
As discussed: the credentials used to "create" the `task` != credentials of the `task`.

See #550 comments for some additional context.
Prevents #550 and #501 from working properly.

**Comment by dacbd** [comment]
https://github.com/iterative/terraform-provider-iterative/pull/550#issuecomment-1118889708

https://github.com/iterative/terraform-provider-iterative/blob/1df59d5c1976cada9a7f7f2fc5fb32777ce979ee/task/common/machine/script.go#L45-L47

https://github.com/iterative/terraform-provider-iterative/blob/1df59d5c1976cada9a7f7f2fc5fb32777ce979ee/task/common/machine/script.go#L130

https://github.com/iterative/terraform-provider-iterative/blob/1df59d5c1976cada9a7f7f2fc5fb32777ce979ee/task/common/machine/script.go#L13-L18

https://github.com/iterative/terraform-provider-iterative/blob/1df59d5c1976cada9a7f7f2fc5fb32777ce979ee/task/common/values.go#L85-L105

https://github.com/iterative/terraform-provider-iterative/blob/1df59d5c1976cada9a7f7f2fc5fb32777ce979ee/task/aws/resources/resource_launch_template.go#L47-L55

**Comment by dacbd** [comment]
> Yes, the action point wouldn't be removing that logic (yet), but just
making it exclusive to ExecStop*

@0x2b3bfa0 Does systemd allow different `EnvironmentFile`s per `Exec*` cmd?
[Or add `:`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=) to the `ExecStart` and monkey patch the proper envs in differently?

**Comment by 0x2b3bfa0** [comment]
It's a bit more involved:

ExecStart should receive all the environment variables except for the
credentials.

ExecStop* should receive all the environment variables.

We may need to differentiate credentials from the rest of variables and
`source` the former only when needed.
