### ISSUE TITLE
timeout: resume timer on spot recovery

### ISSUE THREAD

**Issue by casperdcl** [iterative/terraform-provider-iterative#571]
The `timeout` timer currently resets on spot interrupts.

For example, `timeout=7*24*60*60 # 7days` will likely never be triggered, which defeats the point IMO.

**Comment by 0x2b3bfa0** [comment]
Note that `k8s` already uses a task-scoped deadline and this issue only affects `aws`, `az` and `gcp`

**Comment by dacbd** [comment]
Could we use a timer unit that gets synced with the bucket?

**Comment by casperdcl** [comment]
exactly
