### ISSUE TITLE
Data sync: allow more advanced `workdir` and `output` specs

### ISSUE THREAD

**Issue by dberenbaum** [iterative/terraform-provider-iterative#590]
It would be great for `workdir`/`output` to support:

* Lists of multiple paths
* Globs or regexes

**Comment by 0x2b3bfa0** [comment]
### Related

https://github.com/iterative/terraform-provider-iterative/issues/414#issuecomment-1064016678

**Comment by dacbd** [comment]
+1 for a exclude option,
```hcl
storage {
  workdir = "."
  exclude = [
    ".dvc/cache",
    "venv"
  ]
  output = "./reports"
}
```

**Comment by casperdcl** [comment]
Quick note: `exclude` should be a `list[str]` relative to `workdir`
