### ISSUE TITLE
Allow setting instance tags for cloud providers

### ISSUE THREAD

**Issue by mathematiguy** [iterative/terraform-provider-iterative#598]
One thing I've noticed after looking through the docs here: https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#argument-reference

is that there is no way to assign a tag to an ec2 instance. This is often necessary for billing purposes, so it would be great if there were a way do this.

Thanks for the great work!

**Comment by 0x2b3bfa0** [comment]
* https://github.com/iterative/terraform-provider-iterative/pull/599

**Comment by 0x2b3bfa0** [comment]
@mathematiguy, released with [v0.10.14](https://github.com/iterative/terraform-provider-iterative/releases/tag/v0.10.14), should be available [once the release workflow finishes running](https://github.com/iterative/terraform-provider-iterative/actions/runs/2430292843); you can upgrade by running `terraform init --upgrade`
