### ISSUE TITLE
re-fix `task` NVIDIA drivers

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#606]
Coming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/986933583832813648)

```sh
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

I have confirmed it too.

**Comment by DavidGOrtega** [comment]
duplicated of https://github.com/iterative/cml/issues/1065#issuecomment-1157607462

**Comment by casperdcl** [comment]
Actually... won't TPI `task` need this?

**Comment by casperdcl** [comment]
@dacbd might want to add a basic test for new GPU models to https://github.com/iterative/cml-playground :)

**Comment by dacbd** [comment]
Going to close this, I have now tested with Ampere, Turing, Volta, and Pascal architectures with no issues. The CML created instances where able to perform work and run `nvidia-smi` with no additional or special setup/considerations.
