### ISSUE TITLE
nvidia-docker2 might not be needed

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#674]
> With the release of Docker 19.03, usage of nvidia-docker2 packages is deprecated since NVIDIA GPUs are now natively supported as devices in the Docker runtime.

**Comment by 0x2b3bfa0** [comment]
> [_Note that with the release of Docker 19.03, usage of nvidia-docker2 packages are deprecated since NVIDIA GPUs are now natively supported as devices in the Docker runtime._](https://github.com/NVIDIA/nvidia-docker/blob/36e7a11c52f300668099ee500791e07302810007/README.md?plain=1#L16)

Docker 19.03 introduced the [`--gpus`](https://docs.docker.com/config/containers/resource_constraints/#gpu) option (https://github.com/docker/cli/pull/1714) to replace the old [`--runtime=nvidia`](https://github.com/NVIDIA/nvidia-docker/blob/36e7a11c52f300668099ee500791e07302810007/README.md?plain=1#L75) option.

**Comment by 0x2b3bfa0** [comment]
Replace `nvidia-docker2` with `nvidia-container-toolkit` here:

https://github.com/iterative/terraform-provider-iterative/blob/1e888fbb77b1be0d640ac95dd0df40168b066b20/environment/setup.sh#L40

**Comment by aliabbasjaffri** [comment]
Hello @DavidGOrtega! I would like to take over this issue. Can you please assign it to me?

**Comment by 0x2b3bfa0** [comment]
Yes, sure!

**Comment by aliabbasjaffri** [comment]
Are there any other changes required apart from the one mentioend in the comment above? I tried to look for instances where the old `--runtime` was being used; either in code or readme, but none found.

**Comment by 0x2b3bfa0** [comment]
I think that no other changes are required

**Comment by 0x2b3bfa0** [comment]
After seeing that https://github.com/NVIDIA/nvidia-docker/commit/88a2fda83cb3cf42221931dbd0c08aa4370d4fe5 points to a [documentation page](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker) explicitly requiring the installation of the [allegedly](https://github.com/iterative/terraform-provider-iterative/issues/674#issuecomment-1250008859) deprecated `nvidia-docker2` package, the best thing we can do is question their sanity and close this issue.
