### ISSUE TITLE
SSH into machine like docker-machine

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#73]
Coming from [here](https://discord.com/channels/485586884165107732/728693131557732403/817373843999162369)
> This one's much lower priority, but previously with docker-machine I was able to use docker-machine ssh after creation to install ec2-instance-connect

**Comment by btjones-me** [comment]
Just echoing from the chat, something like this would serve the use case: 
       ```
  cml-runner \
          --cloud aws \
          --cloud-region eu-west-2 \
          --cloud-type=t2.small \
          --cloud-hdd-size 16 \
          --labels=cml-runner
          --custom-data='sudo apt-get install --yes ec2-instance-connect'
```

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega & @btjones-me, would you consider this solved through https://github.com/iterative/cml/issues/438 & https://github.com/iterative/cml/pull/445?

**Comment by DavidGOrtega** [comment]
@btjones-me this is solved but you need to setup it with base64 like azure or aws.

**Comment by btjones-me** [comment]
Hi both sorry for the delay - yes absolutely this is resolved thank you very much

**Comment by 0x2b3bfa0** [comment]
Awesome! Closing as resolved...
