### ISSUE TITLE
Env vars and another unknown

### ISSUE THREAD

**Issue by coyotespike** [iterative/terraform-provider-iterative#744]
Hey y'all,

Thanks for this awesome tool and the fantastic blog posts introducing them.

After cloning the repo, I created `variables.tf` and `terraform.tfvars` files, as I've done for my other projects. Terraform should read environmental variable in from these files, so I put my AWS auth credentials into the `tfvars` file.

Running `apply` gave me this error:

```
TPI [INFO] Creation may take several minutes (consider increasing `timeout` https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#timeout). Please wait.
╷
│ Error: Request cancelled
│ 
│   with iterative_task.example-gpu,
│   on main.tf line 9, in resource "iterative_task" "example-gpu":
│    9: resource "iterative_task" "example-gpu" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-iterative plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x27f9d9f]
```

Exporting them on the command line got me much farther in the process, but then it crashed again.

```
TPI [INFO] Creating resources...                                                            
TPI [INFO] [1/12] Parsing PermissionSet...                                                  
TPI [INFO] [2/12] Importing DefaultVPC...                                                   
TPI [INFO] [3/12] Importing DefaultVPCSubnets...                                            
TPI [INFO] [4/12] Reading Image...                                                          
TPI [INFO] [5/12] Creating Bucket...                                                        
TPI [INFO] [6/12] Creating SecurityGroup...                                                 
TPI [INFO] [7/12] Creating KeyPair...                                                       
TPI [INFO] [8/12] Reading Credentials...                                                    
TPI [INFO] [9/12] Creating LaunchTemplate...                                                
TPI [INFO] [10/12] Creating AutoScalingGroup...                                             
TPI [INFO] [11/12] Uploading Directory...                                                   
TPI [INFO] Transferring 54.74MB (5175 files)...                                             
iterative_task.example-gpu: Still creating... [10s elapsed]
...
iterative_task.example-gpu: Still creating... [4m10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with iterative_task.example-gpu,
│   on main.tf line 9, in resource "iterative_task" "example-gpu":
│    9: resource "iterative_task" "example-gpu" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-iterative plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x27f9d9f]
```

And then a very similar runtime error.

- AWS has actually used my access key, so we got that far
- I tried the little script in the documentation, instead of the fully `train.py` in the example repo, but no love.
- EC2 console shows a bunch of SecurityGroups created and 1 instance still there (with the message "Client.UserInitiatedShutdown: User initiated shutdown")

Would love any help getting the plugin to work!

**Comment by coyotespike** [comment]
@dacbd Sure! All the files are in the link below. But these files are just the examples from the tutorials - there is nothing custom at all.

https://github.com/coyotespike/terraform-scripts/tree/main/cloud-gpu-training

**Comment by 0x2b3bfa0** [comment]
@coyotespike, can you please set the `export TF_LOG=DEBUG` before running any comands and paste the output?

**Comment by coyotespike** [comment]
So I SSH'd into a Digital Ocean Linux machine, cloned my repo and installed Terraform, and ran it.

And what do you know, it worked perfectly! Delightful in itself, and shows the problem is something to do with my local environment/OS. I may try running on another OSX machine tomorrow.

**Comment by dacbd** [comment]
Thanks, I had trouble getting this same exact error. note if you use the leo binary in the releases you can get slightly easier access to your scripts logs, `./leo --cloud was --region us-west-1 read --follow tpi-xxxx`

**Comment by coyotespike** [comment]
Thanks, good to know! I will give that a go

I ran it on an M1 OSX MBP, and it also worked. 

I think it is safe to say there is something odd going on with my local environment (non-M1 OSX). I can't imagine what, I don't have a firewall or anything super weird.

**Comment by coyotespike** [comment]
Okay, I think I am closing in on a solution here. The jobs did not crash in non-local environments, but they did not succeed either.

On Amazon, I have no vCPUs allowed for F spot instances. This fits the behavior observed - the plugin gets all the way through creating a Bucket, SecurityGroup, KeyPair, and so on. And then fails when it actually starts the task, because there are no resources allowed.

AWS standard spot instances are A, C, D, H, I, M, R, T, Z. But as far as I can tell, TPI only fires off requests for F spot instances.

I have put in a request to up the quota/limit for spot instances.

**Comment by dacbd** [comment]
@coyotespike can you share a snippet of what you are doing? Im not exactly sure what you are referring to?

I believe there is a default limit of 256 vCPUs from was per region on was accounts, is this what you are referring to?
