### ISSUE TITLE
Nitpick securityGroup = "cml"

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#77]
In code cml should be replaced with iterative

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 did you had a chance to test [this](https://discord.com/channels/485586884165107732/728693131557732403/818450988084101160) ?

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, unable to reproduce (yet), but trying again the long way.
