### ISSUE TITLE
Broken graceful shutdown when stopping instances from the cloud console

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#90]
[discord](https://discord.com/channels/485586884165107732/728693131557732403/822115520722501632)

Seems that the graceful shutdown is not being called. 
This have been solid working on AWS not in Azure however the report have come from an AWS user.

**Comment by DavidGOrtega** [comment]
I can confirm that Azure still behaves this way

**Comment by 0x2b3bfa0** [comment]
## Azure graceful shutdown process

As per https://azure.microsoft.com/blog/linux-and-graceful-shutdowns-2, virtual machines receive a graceful shutdown command from the hypervisor through the `hv_utils` driver and have five minutes to handle the shutdown process before being terminated forcefully:

#### [`drivers/hv/hv_util.c`](https://github.com/torvalds/linux/blob/1dfb0f47aca11350f45f8c04c3b83f0e829adfa9/drivers/hv/hv_util.c)

* [`static void shutdown_onchannelcallback(void *context)`](https://github.com/torvalds/linux/blob/1dfb0f47aca11350f45f8c04c3b83f0e829adfa9/drivers/hv/hv_util.c#L186-L282)
* [`static void perform_shutdown(struct work_struct *dummy)`](https://github.com/torvalds/linux/blob/1dfb0f47aca11350f45f8c04c3b83f0e829adfa9/drivers/hv/hv_util.c#L166-L169)

#### [`kernel/reboot.c`](https://github.com/torvalds/linux/blob/1dfb0f47aca11350f45f8c04c3b83f0e829adfa9/kernel/reboot.c)

* [`void orderly_poweroff(bool force)`](https://github.com/torvalds/linux/blob/1dfb0f47aca11350f45f8c04c3b83f0e829adfa9/kernel/reboot.c#L488-L501)
* [`static void poweroff_work_func(struct work_struct *work)`](https://github.com/torvalds/linux/blob/1dfb0f47aca11350f45f8c04c3b83f0e829adfa9/kernel/reboot.c#L481-L484)
* [`static int __orderly_poweroff(bool force)`](https://github.com/torvalds/linux/blob/1dfb0f47aca11350f45f8c04c3b83f0e829adfa9/kernel/reboot.c#L458-L477)

In this case, the orderly poweroff process is being handled directly by the `/sbin/poweroff` binary; the only case where the kernel receives an immediate power off signal is when such binary can't be executed or its execution fails with a non-zero exit status.

## System graceful shutdown process

Ubuntu 15.04+ uses [`systemd`](https://www.freedesktop.org/wiki/Software/systemd) to handle system initialization, and `/sbin/poweroff` is just a symbolic link to the `/bin/systemctl` binary, which is able to [detect](https://github.com/systemd/systemd/blob/3c3335c7146a43137c46acfa18417cca101cb088/src/systemctl/systemctl.c#L960-L1015) the call path and [perform different actions](https://github.com/systemd/systemd/blob/5efbd0bf897a990ebe43d7dc69141d87c404ac9a/src/systemctl/systemctl-compat-halt.c#L52-L142) in each case.

After receiving the graceful shutdown notice through the `poweroff` command, the system will try to stop all the running services in a controlled way, as usual. The only difference with the bare metal machines we're used to work with in a local setting is that there is a hard limit of five minutes and, after that time, the virtual machine will be forcefully terminated by the hypervisor.

## Runner graceful shutdown process

So far so good, all the boot processes seem sane enough to allow `cml-runner` to shutdown gracefully. Unfortunately, an `oneshot` service without any explicit dependency won't get the termination signal or, at least, won't get it until it's too late and the network has been stopped.

https://github.com/iterative/terraform-provider-iterative/blob/9fdaf569d18c14dad8b9e25293e631e94ee2311f/iterative/resource_runner.go#L329-L338

**Comment by 0x2b3bfa0** [comment]
Bumping again to critical because this issue is a major blocker for iterative/cml#583

**Comment by DavidGOrtega** [comment]
I can confirm also that AWS termitate in the console does not seem t work either

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, can you try to reproduce the issue with #160? Maybe it's the same for both.
