### ISSUE TITLE
Accept scripts without requiring additional Base64 encoding

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/terraform-provider-iterative#91]
Terraform support for [heredocs](https://www.terraform.io/docs/language/expressions/strings.html#indented-heredocs) and  [files](https://www.terraform.io/docs/language/functions/file.html) would play nicely with literal scripts and wouldn't require users to encode them in advance or resort to [file](https://www.terraform.io/docs/language/functions/filebase64.html) and [string encoding functions](https://www.terraform.io/docs/language/functions/base64encode.html). We might still use the latter internally for foolproof escaping of templated files, but users should be able of writing plain scripts manually.

**Comment by DavidGOrtega** [comment]
I think is not a great idea.
All the vendors enforces you to base64 is not nothing new and also for the cml-runner command is going to be a mess

**Comment by 0x2b3bfa0** [comment]
Ideally, performing the following modification to the pertaining template line would be enough on the CML side:
[``${startup_script ? `startup_script = base64decode("${startup_script}")` : ''}``](https://github.com/iterative/cml/blob/5888e49d55662aafd20f62d9acf5ecc2c5478a43/src/terraform.js#L106)
I thought it could be a good move for the user experience, but I don't know. 🤷‍♂️

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0  Its breaking CML but also basic terraform provider. Now the TPI is not accepting the base64 encoded script.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 one of the main reasons also is that base64 is far more robust than this heredoc. It's terribly painful to make this work through a template

**Comment by DavidGOrtega** [comment]
> but users should be able of writing plain scripts manually.

Users have been able to use custom script in Azure and AWS in base64 so we are worse!

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, given that the provider still is in its early stages of development, I think that we can afford introducing this change without breaking anything.

As stated [above](https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-804783976), CML wouldn't have to use the here document syntax and can continue to provide scripts in Base64 to avoid string escaping issues.

**Comment by 0x2b3bfa0** [comment]
### Follow-up of #168

Currently, `resource_cml_runner` takes Base64-encoded scripts, while `resource_machine` takes raw scripts. Independently of the approach we choose, it should be the same for both resources. I would prefer to modify the former to behave like the latter.

**Comment by omesser** [comment]
@0x2b3bfa0 @DavidGOrtega 
Why not have both in a consistent, explicit manner - 2 separate fields: `startup_script` and `startup_script_base64` .
If both fields are non-`""` it will fail (no guessing!)

**Comment by 0x2b3bfa0** [comment]
> _Why not have both in a consistent, explicit manner - 2 separate fields_

Because Terraform has an inbuilt [`base64decode`](https://www.terraform.io/language/functions/base64decode) function with this exact purpose.

**Comment by omesser** [comment]
Yeah, obviously, but not sure I follow what are you suggesting wrt the choice of whether to expect file contents encoded or not.
b64 codec'ing is easy both for the user and for us, so why take away the benefit of giving the user the flexibility to provide the script either base64 encoded or not?

**Comment by 0x2b3bfa0** [comment]
> _not sure I follow what are you suggesting wrt the choice of whether to expect file contents encoded or not_

I propose[^1] to accept raw scripts in both `iterative_machine` & `iterative_cml_runner` and drop support for Base64–encoded data. Currently, `iterative_machine` expects raw scripts and `iterative_cml_runner` expects Base64–encoded scripts. 🙃 

> _b64 codec'ing is easy both for the user and for us, so why take away the benefit of giving the user the flexibility to provide the script either base64 encoded or not?_

Expecting only raw scripts doesn't _take away any benefits:_ it just avoids polluting the API with a redundant argument.

### Common
This is what users would do in both cases; i.e. when the script is not encoded.

#### Raw [String](https://www.terraform.io/language/expressions/types#string)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = "IyEvYmluL3NoCmVjaG8gdGFzdGVmdWwK"
}
```
#### Raw [Heredoc](https://www.terraform.io/language/expressions/strings#indented-heredocs)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = <<-END
    #!/bin/sh
    echo tasteful
  END
}
```
#### Raw [File](https://www.terraform.io/docs/language/functions/file.html)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = file("${path.root}/tasteful.sh")
}
```
### Different Arguments
This is what users would have to do when the script is Base64–encoded, if the resource implements a separate Base64 decoding argument.
#### Base64 [String](https://www.terraform.io/language/expressions/types#string)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script_base64 = "IyEvYmluL3NoCmVjaG8gbm90IHF1aXRlCg=="
}
```
#### Base64 [Heredoc](https://www.terraform.io/language/expressions/strings#indented-heredocs)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script_base64 = <<-END
    IyEvYmluL3NoCmVjaG8gbm90IHF1aXRlCg==
  END
}
```
#### Base64 [File](https://www.terraform.io/docs/language/functions/file.html)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script_base64 = file("${path.root}/not_quite.sh.base64")
}
```

### Raw Only
This is what users would have to do when the script is Base64–encoded, using the builtin functions.
#### Base64 [String](https://www.terraform.io/language/expressions/types#string)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = base64decode("IyEvYmluL3NoCmVjaG8gdGFzdGVmdWwK")
}
```
#### Base64 [Heredoc](https://www.terraform.io/language/expressions/strings#indented-heredocs)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = base64decode(
    <<-END
      IyEvYmluL3NoCmVjaG8gdGFzdGVmdWwK
    END
  )
}
```
#### Base64 [File](https://www.terraform.io/docs/language/functions/file.html)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = filebase64("${path.root}/tasteful.sh.base64")
}
```

[^1]: https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-912951829, not that important since #462 anyway.

**Comment by 0x2b3bfa0** [comment]
### Common
This is what users would do in both cases; i.e. when the script is not encoded.

#### Raw [String](https://www.terraform.io/language/expressions/types#string)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = "IyEvYmluL3NoCmVjaG8gdGFzdGVmdWwK"
}
```
#### Raw [Heredoc](https://www.terraform.io/language/expressions/strings#indented-heredocs)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = <<-END
    #!/bin/sh
    echo tasteful
  END
}
```
#### Raw [File](https://www.terraform.io/docs/language/functions/file.html)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = file("${path.root}/tasteful.sh")
}
```
### Different Arguments
This is what users would have to do when the script is Base64–encoded, if the resource implements a separate Base64 decoding argument.
#### Base64 [String](https://www.terraform.io/language/expressions/types#string)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script_base64 = "IyEvYmluL3NoCmVjaG8gbm90IHF1aXRlCg=="
}
```
#### Base64 [Heredoc](https://www.terraform.io/language/expressions/strings#indented-heredocs)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script_base64 = <<-END
    IyEvYmluL3NoCmVjaG8gbm90IHF1aXRlCg==
  END
}
```
#### Base64 [File](https://www.terraform.io/docs/language/functions/file.html)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script_base64 = file("${path.root}/not_quite.sh.base64")
}
```

### Raw Only
This is what users would have to do when the script is Base64–encoded, using the builtin functions.
#### Base64 [String](https://www.terraform.io/language/expressions/types#string)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = base64decode("IyEvYmluL3NoCmVjaG8gdGFzdGVmdWwK")
}
```
#### Base64 [Heredoc](https://www.terraform.io/language/expressions/strings#indented-heredocs)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = base64decode(
    <<-END
      IyEvYmluL3NoCmVjaG8gdGFzdGVmdWwK
    END
  )
}
```
#### Base64 [File](https://www.terraform.io/docs/language/functions/file.html)
```hcl
resource "iterative_cml_runner" "example" {
  startup_script = filebase64("${path.root}/tasteful.sh.base64")
}
```

**Comment by omesser** [comment]
@0x2b3bfa0  - due to [this](https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-886892321) I suggest to think whether it's worth to drop the support.
I can think of a few scenarios where it's worth to have this base64 support in place, I'm not sure how relevant they are though:
- When programmatically generating tf configs and templating values into them, much easier to work and template in a b64 string
- CLI support - If this can be populated in any scenario by an input var e.g. `terraform apply -var 'X.Y. startup_script_base64=<stuff>'

**Comment by 0x2b3bfa0** [comment]
> _When programmatically generating tf configs and templating values into them_

See https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-804783976; it's as easy as `startup_script = base64decode("{{startup_script_base64}}")` ...batteries included.

**Comment by 0x2b3bfa0** [comment]
> _CLI support - If this can be populated in any scenario by an input var e.g. `terraform apply -var 'startup_script_base64=<stuff>'`_

For valid UTF–8 strings not containing [`\0`](https://en.wikipedia.org/wiki/Null_character) there is no need for Base64 encoding. If there was such a need, it's always possible to use the aforementioned inbuilt functions.

```hcl
variable "input" {
}

output "output" {
  value = base64decode(var.input)
}
```

```console
terraform apply -var input="$(base64 input)"
```

**Comment by omesser** [comment]
With the risk of repeating the point a bit
Agreed the `bas64decode` function exists and things can be decoded in various places and achieved either way.
The point I'm making is about user experience -  Giving users what they expect and keeping their syntax clean and flat.

I don't think that this
```tf
startup_script = base64decode("{{startup_script_base64}}")
```
is an [equally convenient](https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-1094421826) alternative to this:
```tf
startup_script_base64 = "{{startup_script_base64}}"
```
And saving the user the need to convert their input is a good perk UX wise, when hitting a common use cases, and if I catch the drift here, it can be very common.

It might be worth "polluting the api" with another (optional) field.
Granted, this is opinionated, but do consider please - making lives easier for users with a clean interface they will actually look at vs 1 less optional field (what are the operational costs of this? for them? for us?).

Same thing in CLI `-var input="$(base64 input)"` vs `-var input_base64="input"` - first option is cumbersome and most people don't enjoy shell fun-times. This would have been much worse in a non-toy example (i.e. real contents in `input`) - escaping a script's content to put it as a raw string in a shell command is a nice sight to behold (hence not a good practice), base64 is very often used as a catch-all to avoid escaping issues even though the contents can be properly escaped if you care to spend the time (ML engineers won't, right?).

This might save the users a few minutes scratching their heads building the tf config and the code/commands around it, and more importantly, keeping terraform configs as flat+simple as possible on the user end, so they can debug their inputs outside of terraform and get full easy visibility to what the provider gets as inputs / vars.
Also, there's the upside of eliminating ambiguity as per what does `startup_script` expect (raw or base64), due to the existence of `startup_script_base64` - seeing both in the docs makes it all clear. Same goes, btw for `startup_script_file` - these are basically convenient wrappers. The fact that 2 approaches [were mixed](https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-912951829) means that there is place for ambiguity and it might be nice to reduce it

**Comment by casperdcl** [comment]
I'm also leaning towards [this](https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-1094339203)

- `startup_script`: change to expect raw (affects CML)
- `startup_script_base64`: new, expects base64 (CML would switch to using this)

**Comment by 0x2b3bfa0** [comment]
> _The point I'm making is about user experience - Giving users what they expect and keeping their syntax clean and flat._

If we're talking of existing Terraform power users, it looks like we have irreconcilliable differences with regard to their expectations. 😅 

> _I don't think that this_ [`startup_script = base64decode("data")`] _is an equally convenient alternative to this_ [`startup_script_base64 = "data"`]

Neither do I: to my mind, the former is much more convenient both for users and for ourselves. 😈 

> _And saving the user the need to convert their input is a good perk UX wise, when hitting a common use cases, and if I catch the drift[^1] here, it can be very common._

Providing a Base64–encoded script is not a valid[^2] use case, unless proven otherwise. It's just something we do internally on CML to avoid the need of escaping our [runner templates](https://github.com/iterative/cml/blob/fdfcb1bbb50e1acb531273fd8b4fb9117012c845/src/terraform.js#L115).

If this argument accepted arbitrary binary data (as opposed to UTF–8 text) for this use case, it would [make sense](https://www.terraform.io/language/functions/filebase64) to use Base64 as the only input format, but this is not the case.

Unlike what you probably believe, this argument is not mapped to the [cloud–init user data](https://cloudinit.readthedocs.io/en/latest/topics/format.html) value read by cloud instances. It's just being inserted in the middle of a templated script, and providing binary data wouldn't have other effect beyond upsetting the shell interpreter:
https://github.com/iterative/terraform-provider-iterative/blob/2dd6c603529880ce3f942d44d916ff03f1dbce12/iterative/resource_runner.go#L340-L342

Moreover, the current approach is doubly inconvenient: the primary use case for this Terraform resource is powering the [`cml runner`](https://cml.dev/doc/ref/runner) command, and this particular argument is exposed through the [`--cloud-startup-script`](https://cml.dev/doc/ref/runner) command–line option, which _“run[s] the provided Base64-encoded Linux shell script during the instance initialization”,_ so users need[^3] to run `cml runner --cloud-startup-script="$(base64 --wrap 0 <<< 'echo hello world')"` and take care of encoding; that _is_ bad user experience.

### User Data

Just for reference, the official AWS provider accepts both forms, exactly like in [your proposal](https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-1094339203), although other providers only take plain text.

* **Amazon Web Services: [aws_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance) exposes both [`user_data`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data
) and [`user_data_base64`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_base64)**
   > _Use this_ [`user_data_base64`] _instead of `user_data` whenever the value is not a valid UTF-8 string. For example, gzip-encoded user data must be base64-encoded and passed via this argument to avoid corruption._

* **Microsoft Azure: [`azurerm_virtual_machine`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine) exposes only [`custom_data`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#custom_data) which expects a raw string**
   > _Internally, Terraform will base64 encode this value before sending it to the API._

* **Google Cloud: [`google_compute_instance`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance) [`metadata_startup_script`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#metadata_startup_script)  which expects a raw string**

[^1]: The best cloud infrastructure pun I have ever seen! 😂 
[^2]: Replace with “common” if it sounds like a baseless value judgement
[^3]: See [cml#536 (comment)](https://github.com/iterative/cml/issues/536#issuecomment-843954822) and [cml#772 (comment)](https://github.com/iterative/cml/issues/772#issuecomment-1014958065) for hitorical evidence

**Comment by 0x2b3bfa0** [comment]
> _The fact that 2 approaches [were mixed](https://github.com/iterative/terraform-provider-iterative/issues/91#issuecomment-912951829) means that there is place for ambiguity and it might be nice to reduce it_

Indeed, it might be nice to reduce it, by aligning their behavior 😄

**Comment by 0x2b3bfa0** [comment]
Given the status of the current API, this can be safely demoted to <kbd>p2-nice-to-have</kbd> and will be addressed tangentially when reworking the `cml runner --cloud` internals.

**Comment by dacbd** [comment]
I think this can just be closed.
- `iterative_machine` is essentially deprecated / will be significantly reworked if used when we make another go at the dvc machine ideas.
- `iterative_runner` is not intended to be used by a user directly and this type of script logic can just be handled by cml when it builds it's `main.tf` internally.

**Comment by casperdcl** [comment]
I thouggt this issue about allowing `cml runner launch --cloud-startup-script` to be plaintext?

**Comment by dacbd** [comment]
> I thought this issue about allowing `cml runner launch --cloud-startup-script` to be plaintext?

even if it is, that shouldn't require any changes to tpi like has been discussed in this thread. There is already a related issue on cml to accept a file for that parameter. plaintext, base64, or file don't need different interfaces in the terraform scheme for the `iterative_runner` resource, they can all use the same one.

**Comment by casperdcl** [comment]
https://github.com/iterative/cml/issues/1167 indeed
