### ISSUE TITLE
AMI fallback script is happening with provider mapped regions

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/terraform-provider-iterative#99]
If I set a "iterative region" like us-west the full script with CUDA installation is happening

**Comment by 0x2b3bfa0** [comment]
> [_Hello I am trying to set up the example: https://gitlab.com/iterative.ai/cml-runner-example for gitlab in my company and I am receiving the following error while running cml-runner: Somebody got experience with this error?_](https://discord.com/channels/485586884165107732/728693131557732403/832273545449963551) As seen on Discord™
> ```console
> $ cml-runner --cloud aws --cloud-region us-west --cloud-type t2.micro --labels=cml-runner
> Preparing workdir /home/runner...
> Deploying cloud runner plan...
> Terraform apply...
> {"level":"error","status":"terminated"}
> Error: terraform -chdir='/home/runner' apply -auto-approve
> 	iterative_cml_runner.runner: Creating...
> iterative_cml_runner.runner: Still creating... [10s elapsed]
> iterative_cml_runner.runner: Still creating... [20s elapsed]
> iterative_cml_runner.runner: Still creating... [30s elapsed]
> iterative_cml_runner.runner: Still creating... [40s elapsed]
> iterative_cml_runner.runner: Still creating... [50s elapsed]
> iterative_cml_runner.runner: Still creating... [1m0s elapsed]
> iterative_cml_runner.runner: Still creating... [1m10s elapsed]
> iterative_cml_runner.runner: Still creating... [1m20s elapsed]
> iterative_cml_runner.runner: Still creating... [1m30s elapsed]
> iterative_cml_runner.runner: Still creating... [1m40s elapsed]
> iterative_cml_runner.runner: Still creating... [1m50s elapsed]
> iterative_cml_runner.runner: Still creating... [2m0s elapsed]
> iterative_cml_runner.runner: Still creating... [2m10s elapsed]
> iterative_cml_runner.runner: Still creating... [2m20s elapsed]
> iterative_cml_runner.runner: Still creating... [2m30s elapsed]
> iterative_cml_runner.runner: Still creating... [2m40s elapsed]
> iterative_cml_runner.runner: Still creating... [2m50s elapsed]
> iterative_cml_runner.runner: Still creating... [3m0s elapsed]
> iterative_cml_runner.runner: Still creating... [3m10s elapsed]
> iterative_cml_runner.runner: Still creating... [3m20s elapsed]
> iterative_cml_runner.runner: Still creating... [3m30s elapsed]
> iterative_cml_runner.runner: Still creating... [3m40s elapsed]
> iterative_cml_runner.runner: Still creating... [3m50s elapsed]
> iterative_cml_runner.runner: Still creating... [4m0s elapsed]
> iterative_cml_runner.runner: Still creating... [4m10s elapsed]
> iterative_cml_runner.runner: Still creating... [4m20s elapsed]
> iterative_cml_runner.runner: Still creating... [4m30s elapsed]
> iterative_cml_runner.runner: Still creating... [4m40s elapsed]
> iterative_cml_runner.runner: Still creating... [4m50s elapsed]
> iterative_cml_runner.runner: Still creating... [5m0s elapsed]
> iterative_cml_runner.runner: Still creating... [5m10s elapsed]
> iterative_cml_runner.runner: Still creating... [5m20s elapsed]
> iterative_cml_runner.runner: Still creating... [5m30s elapsed]
> iterative_cml_runner.runner: Still creating... [5m40s elapsed]
> iterative_cml_runner.runner: Still creating... [5m50s elapsed]
> iterative_cml_runner.runner: Still creating... [6m0s elapsed]
> iterative_cml_runner.runner: Still creating... [6m10s elapsed]
> iterative_cml_runner.runner: Still creating... [6m20s elapsed]
> iterative_cml_runner.runner: Still creating... [6m30s elapsed]
> iterative_cml_runner.runner: Still creating... [6m40s elapsed]
> iterative_cml_runner.runner: Still creating... [6m50s elapsed]
> iterative_cml_runner.runner: Still creating... [7m0s elapsed]
> iterative_cml_runner.runner: Still creating... [7m10s elapsed]
> iterative_cml_runner.runner: Still creating... [7m20s elapsed]
> iterative_cml_runner.runner: Still creating... [7m30s elapsed]
> iterative_cml_runner.runner: Still creating... [7m40s elapsed]
> iterative_cml_runner.runner: Still creating... [7m50s elapsed]
> iterative_cml_runner.runner: Still creating... [8m0s elapsed]
> iterative_cml_runner.runner: Still creating... [8m10s elapsed]
> iterative_cml_runner.runner: Still creating... [8m20s elapsed]
> iterative_cml_runner.runner: Still creating... [8m30s elapsed]
> iterative_cml_runner.runner: Still creating... [8m40s elapsed]
> iterative_cml_runner.runner: Still creating... [8m50s elapsed]
> iterative_cml_runner.runner: Still creating... [9m0s elapsed]
> iterative_cml_runner.runner: Still creating... [9m10s elapsed]
> iterative_cml_runner.runner: Still creating... [9m20s elapsed]
> iterative_cml_runner.runner: Still creating... [9m30s elapsed]
> iterative_cml_runner.runner: Still creating... [9m40s elapsed]
> iterative_cml_runner.runner: Still creating... [9m50s elapsed]
> iterative_cml_runner.runner: Still creating... [10m0s elapsed]
> iterative_cml_runner.runner: Still creating... [10m10s elapsed]
> iterative_cml_runner.runner: Still creating... [10m20s elapsed]
> 	
> Error: Error checking the runner status
>   on main.tf line 14, in resource "iterative_cml_runner" "runner":
>   14: resource "iterative_cml_runner" "runner" {
> dial tcp 13.56.197.103:22: i/o timeout
>     at /cml/src/utils.js:15:27
>     at ChildProcess.exithandler (child_process.js:315:5)
>     at ChildProcess.emit (events.js:314:20)
>     at maybeClose (internal/child_process.js:1022:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
> iterative_cml_runner.runner: Destroying... [id=iterative-ori4bxlkpo3d]
> iterative_cml_runner.runner: Destruction complete after 1s
> Destroy complete! Resources: 1 destroyed.
> Cleaning up file based variables
> 00:01
> ERROR: Job failed: exit code 1
> ```
